"""Verification and human review are independent judgments."""

LLM_ONLY_OPERATORS = frozenset({
    "event_specialization", "measure_specialization", "capability_refinement", "new_rule_generation"
})


def method_error(patch):
    if patch.get("operation") == "concern_completion":
        return "Deterministic concern completion was removed: it is outside the paper methodology."
    if patch.get("operation") in LLM_ONLY_OPERATORS and patch.get("source") != "llm":
        return "The paper requires this semantic operator to be generated by the LLM."
    return ""


def formally_verified(patch):
    return (not method_error(patch) and patch.get("verified") is True
            and patch.get("syntax_validation", {}).get("valid") is True
            and patch.get("regression_report", {}).get("regression_passed") is True
            and patch.get("target_fixed") is True)


def update_candidate_status(patch):
    error = method_error(patch)
    if error:
        patch.update(verified=False, failure_reason=error)
    syntax = patch.get("syntax_validation", {}).get("valid")
    verified = formally_verified(patch)
    patch["verified"] = verified
    patch["syntax_valid"] = syntax if type(syntax) is bool else None
    patch["formally_verified"] = verified
    if verified:
        status = "formally_verified"
    elif patch.get("verification_inconclusive"):
        status = "inconclusive"
    elif patch.get("failure_reason"):
        status = "rejected"
    elif syntax is True:
        status = "syntax_valid"
    else:
        status = "generated"
    patch["candidate_status"] = status
    # Software checks cannot approve the stakeholder meaning of a proposal.
    review = patch.get("source") == "llm" or patch.get("operation") not in {"rule_removal", "delete_redundant_rule"}
    patch["semantic_review_status"] = "pending" if review else "not_required"
    patch["requires_social_scientist_review"] = review
    return patch
