import json
import re


PATCH_OUTPUT_FORMAT = """
Return ONLY a raw JSON array.

The repair operator has already been selected by SLEEC-PATCH.

Your task is to instantiate that selected operator and generate the
missing semantic/syntactic element required by it.

Each candidate patch MUST use this structure:

[
  {
    "patch_id": "p1",
    "issue_type": "<diagnosed issue type>",
    "operation": "<selected repair operator>",

    "target_rule_id": "<target rule id, or empty only when the selected operator creates a new rule>",
    "original_rule": "<exact original SLEEC rule, or empty only when the selected operator creates a new rule>",

    "missing_element": "<the semantic/syntactic element generated by the selected operator>",
    "proposed_rule": "<complete candidate SLEEC rule containing the generated element>",

    "grounding_evidence": {
      "source": "<system_description|diagnosis|witness|existing_vocabulary>",
      "source_terms": [
        "<exact supporting term or formal identifier from the claimed source>"
      ],
      "existing_element": "<existing element being specialized/refined, or empty for new-rule generation when appropriate>",
      "new_element": "<the generated semantic/syntactic element>",
      "relationship": "<how the cited evidence supports the generated element>"
    },

    "natural_language_explanation": "<brief explanation of how the generated element instantiates the selected repair operator for the diagnosed WFI>",

    "modification_cost": 1,
    "new_events_added": 0,
    "new_measures_added": 0,
    "new_capabilities_added": 0,
    "new_rules_added": 0,
    "defeaters_added": 0
  }
]

IMPORTANT:

- The selected repair operator is fixed. Do not choose another operator.
- Generate only the semantic/syntactic element required by that operator.
- Do not claim that the candidate is formally correct or verified.
- Do not claim that the targeted WFI has been eliminated.
- Do not claim that the candidate introduces no additional WFIs.
- Formal correctness is determined later by SLEEC-PATCH through
  LEGOS-SLEEC re-analysis.
- Do not modify unrelated rules.
- Set the *_added fields according to the actual candidate repair.
- Do NOT use markdown.
- Do NOT use ```json.
- Do NOT add text before or after the JSON.
- The response MUST start with [ and end with ].
"""


LLM_SEMANTIC_OPERATORS = [
    # Redundancy
    "redundancy_event_specialization",
    "redundancy_measure_specialization",

    # Concern / insufficiency
    "concern_new_rule_generation",

    # Purpose blocking / restrictiveness
    "purpose_capability_refinement",

    # Situational conflict
    "conflict_event_specialization",
    "conflict_measure_specialization",
    "semantic_rule_merging",
]


def build_sleec_syntax_bank(rules):
    rules = rules or []
    rule_texts = [
        str(rule.get("raw") or rule.get("text") or "").strip()
        if isinstance(rule, dict)
        else str(rule or "").strip()
        for rule in rules
    ]
    rule_texts = [text for text in rule_texts if text]

    observed = []
    if any(" unless " in text.lower() for text in rule_texts):
        observed.append("unless exceptions with optional alternative responses")
    if any(" within " in text.lower() for text in rule_texts):
        observed.append("within time bounds")
    if any(re.search(r"\{[A-Za-z_][A-Za-z0-9_]*\}", text) for text in rule_texts):
        observed.append("boolean measures wrapped in braces")
    if any(re.search(r"\{?[A-Za-z_][A-Za-z0-9_]*\}?\s*[<>=]\s*[A-Za-z0-9_]+", text) for text in rule_texts):
        observed.append("measure comparisons")
    if any(re.search(r"\b(?:and|or|not)\b", text, flags=re.IGNORECASE) for text in rule_texts):
        observed.append("and/or/not logical conditions")

    examples = rule_texts[:5]

    return {
        "allowed_rule_templates": [
            "RuleName when Trigger then Action",
            "RuleName when Trigger and Condition then Action",
            "RuleName when Trigger then Action within Number seconds",
            "RuleName when Trigger then Action unless Condition",
            "RuleName when Trigger then Action unless Condition then AlternativeAction",
        ],
        "observed_syntax_features": observed,
        "local_rule_examples": examples,
        "instruction": (
            "Use only these observed SLEEC syntax forms and the supplied "
            "vocabulary. Do not invent grammar constructs."
        )
    }


SLEEC_SYNTAX_CONTRACT = """
SLEEC SYNTAX CONTRACT:
Use only the SLEEC syntax already present in the input specification.

Allowed declaration lines:
- event EventName
- measure measureName:boolean
- measure measureName:numeric
- constant ConstantName = value

Allowed rule shapes:
- RuleName when Trigger then Action
- RuleName when Trigger and Condition then Action
- RuleName when Trigger then Action within Number seconds
- RuleName when Trigger then Action
       unless Condition then AlternativeAction
- RuleName when Trigger then Action
       unless Condition

Allowed condition syntax:
- "and" may combine trigger events and supported conditions.
- "not" may negate supported boolean conditions.
- "or" is allowed only inside supported condition/measure expressions;
  it must NOT be used to combine alternative trigger events.
- parentheses for grouping supported condition/measure expressions
- boolean measures as {measureName}
- numeric comparisons such as {measureName} > ConstantName

IMPORTANT EVENT-TRIGGER RESTRICTION:
- A SLEEC rule has exactly ONE trigger event immediately after "when".

- After the trigger event, "and" may introduce only a supported
  condition/measure expression. It must NOT introduce another event.

- Do NOT write:
      when EventA or EventB then Action

- Do NOT write:
      when EventA and EventB then Action

- VALID shapes include:
      when EventA then Action
      when EventA and {{measureA}} then Action
      when EventA and (not {{measureA}}) then Action
      when EventA and ({{measureA}} or {{measureB}}) then Action

- INVALID shapes include:
      when EventA or EventB then Action
      when EventA and EventB then Action

- Event names are NOT boolean conditions and must not be placed after
  "and", "or", or "not" as if they were measures.

- Alternative trigger events cannot be combined into one trigger using
  either "and" or "or".

- If a repair requires combining two different trigger events and no
  equivalent repair can be expressed using one existing trigger event
  plus grounded measure conditions, defeaters, responses, or temporal
  constraints, do NOT invent a merged rule. Return no candidate.

Forbidden syntax:
- Do not use IF, ELSE, REQUIRES, BECAUSE, SHOULD, MUST, UNTIL, EXCEPT, IMPLIES, or arrows.
- Do not invent new SLEEC keywords.
- Do not put prose, bullet points, or comments inside proposed_rule.
- Do not wrap the whole rule in parentheses.
- Do not output def_start, def_end, rule_start, or rule_end inside proposed_rule.
- Do not output declaration lines inside proposed_rule.

Vocabulary accounting:
- If missing_element is a new event, set new_events_added to 1.
- If missing_element is a new measure, set new_measures_added to 1.
- If missing_element is a new response/capability, set new_capabilities_added to 1.
- If the patch adds a new rule, set new_rules_added to 1.
- Otherwise the corresponding counter must be 0.

The generated candidate must follow this syntax contract exactly.
Do not invent new SLEEC syntax to express the selected repair operator.
"""


SLEEC_FEW_SHOT_SYNTAX_EXAMPLES = """
FEW-SHOT SLEEC SYNTAX EXAMPLES:
These examples teach syntax shape only. Do not copy their domain vocabulary.

Example 1: edit an existing event trigger
Original rule:
r1 when BroadEvent then SafeAction
Correct proposed_rule:
r1 when SpecificEvent then SafeAction

Example 2: preserve an unless branch
Original rule:
r2 when RequestAction then DoAction
   unless {unsafeState} then StopAction
Correct proposed_rule:
r2 when SpecificRequestAction then DoAction
   unless {unsafeState} then StopAction

Example 3: preserve temporal syntax
Original rule:
r3 when EmergencyEvent then NotifyHuman within 60 seconds
Correct proposed_rule:
r3 when SpecificEmergencyEvent then NotifyHuman within 60 seconds

Example 4: add one new rule
Correct proposed_rule:
r_new when MissingConditionEvent and {relevantState} then RequiredAction

"""



OPERATOR_EXAMPLES = {

'event_specialization': '''EXAMPLE: EVENT SPECIALIZATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
Different emergency events may require different responses.
A fire-related emergency and a human-on-floor emergency must not
automatically be treated as the same situation.

Original conflicting rules:

r1 when SmokeDetectorAlarm
   then CallEmergencyServices within 5 minutes

r2 when HumanOnFloor and not humanAssents
   then not CallEmergencyServices within 500 seconds

Diagnosis:
A witness shows that a smoke alarm can occur while a human is on the floor
without assent. The two rules can therefore become applicable while requiring
conflicting behaviour concerning CallEmergencyServices.

Selected operator:
event_specialization

Semantic distinction:
SmokeDetectorAlarm and HumanOnFloor represent different event contexts.

The purpose of event specialization is to distinguish the partially
conflicting behaviours associated with these event contexts.

Do NOT interpret SmokeDetectorAlarm as a specialization of HumanOnFloor.
Do NOT interpret HumanOnFloor as a specialization of SmokeDetectorAlarm.

The diagnosed events establish the event contexts that must be
distinguished; one event must not simply replace the other.

Grounded repair pattern:

If the supplied ALMI vocabulary and system description support a
fire-specific response such as CallingFireMan, the behaviour associated
with SmokeDetectorAlarm may be specialized:

r1 when SmokeDetectorAlarm
   then CallingFireMan within 5 minutes

while the HumanOnFloor rule remains associated with its own emergency
context.

This distinguishes the fire-related behaviour from the human-on-floor
emergency behaviour instead of imposing the human-assent condition on
the fire-related event.

IMPORTANT:

Do NOT generate:

SmokeDetectorAlarmWithoutHumanAssent
SmokeDetectorAlarmWhileHumanOnFloor
HumanOnFloorFireEmergency

merely by combining existing event names with diagnosis text.

Do NOT infer that CallingFireMan requires human assent merely because
humanAssents occurs in the HumanOnFloor rule.

Do NOT transfer contextual restrictions from one diagnosed event context
to another unless the supplied diagnosis, witness, or system description
explicitly supports that transfer.

Use only events and responses grounded in the supplied current-use-case
vocabulary or system description.

Preserve unaffected temporal constraints, contextual conditions, and
defeaters.

Modify only the behaviour necessary to instantiate the selected
event_specialization operator.

The generated candidate is not assumed to be formally correct.
SLEEC-PATCH will apply it to the original specification and use
LEGOS-SLEEC re-analysis to determine whether the diagnosed WFI is
eliminated without introducing additional WFIs.''',

'measure_specialization': '''EXAMPLE: MEASURE SPECIALIZATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:

r4 when SmokeDetectorAlarm and not humanConfirm
   then CallEmergencyServices within 5 minutes

r5 when HumanOnFloor and not humanConfirm
   then not CallEmergencyServices within 500 seconds

Diagnosis:
Both behaviours contain contextual information represented by
humanConfirm. The diagnosed conflict requires a more discriminative
environmental/contextual distinction.

Selected operator:
measure_specialization

Generation task:
Use the diagnosis and witness to determine what environmental/contextual
distinction is required.

Generate only the grounded, more discriminative measure required by the
selected operator.

Search existing_measures first. A new measure may be generated from the
system description only when the environmental/contextual concept is
explicitly and unambiguously supported there.

For example, ALMI may contain distinctions involving concepts such as:

humanAssent

or:

humanConscious

These concepts must NOT be introduced merely because they appear useful.
They may be used only when grounded in the supplied current-use-case input.

The diagnosis and witness identify WHY measure specialization is required.
Their natural-language wording must not automatically be converted into
a new measure.

Preserve:
- the relevant event;
- the response;
- the temporal constraint;
- unrelated conditions; and
- defeaters.

Do NOT invent an environmental predicate merely to force a candidate.''',


'capability_refinement': '''EXAMPLE: CAPABILITY REFINEMENT — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
The specification contains emergency-related responses such as:

CallingFireMan

and:

CallEmergencyServices

These responses represent different system capabilities and must not
automatically be treated as interchangeable.

Example rule:

r1 when SmokeDetectorAlarm
   then CallEmergencyServices within 5 minutes

Diagnosis:
The diagnosed behaviour requires a more specific response than the broad
CallEmergencyServices capability.

Selected operator:
capability_refinement

Generation task:
Use the diagnosis and witness to determine what response distinction is
required.

Generate only the grounded, more-specific capability required by the
selected operator.

Search existing_responses first. A new capability may be generated from
the system description only when the capability is explicitly and
unambiguously supported there.

For example, if the supplied current-use-case evidence establishes
CallingFireMan as the required more-specific response for the diagnosed
fire-related behaviour, it may be used as the refined capability.

Do NOT invent capabilities such as:

CallSpecialEmergencyServices
CallEmergencyServicesForFire
CallEmergencyServicesForUnconsciousHuman

unless those capabilities are explicitly supported by the supplied
current-use-case evidence.

The diagnosis and witness identify WHY capability refinement is required.
Their natural-language wording must not automatically be converted into
a new capability.

Preserve:
- the trigger;
- contextual conditions;
- the temporal constraint; and
- defeaters.

Change only the response required by capability_refinement.''',


'new_rule_generation': '''EXAMPLE: NEW RULE GENERATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
The specification contains emergency situations such as:

HumanOnFloor

and system responses such as:

CallEmergencyServices

Diagnosis:
A LEGOS-SLEEC witness identifies missing normative behaviour involving
HumanOnFloor that must be addressed by an additional rule.

Selected operator:
new_rule_generation

Generation task:
Use the diagnosed rules, witness, diagnosis, system description, and
existing vocabulary to identify the missing normative behaviour.

Generate only the additional normative rule required by the selected
operator.

Every element used in the generated rule must be grounded:
- events in existing_events or explicitly supported by system_description;
- measures in existing_measures or explicitly supported by system_description;
- responses in existing_responses or explicitly supported by system_description.

Grounded structural pattern:

If the supplied diagnosis, witness, existing vocabulary, and ALMI system
description establish that HumanOnFloor requires CallEmergencyServices,
the following form illustrates the operator:

r_new when HumanOnFloor
      then CallEmergencyServices

This is a structural example only.
The current-use-case evidence must justify the generated normative behaviour.

Do NOT invent unsupported responses such as:

CallDoctor

and do NOT invent contextual predicates such as:

{patientCritical}
{hospitalAvailable}
{familyPermission}

unless those concepts are explicitly grounded in the supplied
current-use-case evidence.

Do not create unnecessary new events, measures, or capabilities.

The generated rule must directly address the diagnosed witness concern
and must not duplicate an existing rule.

Formal correctness of the generated candidate is determined later by
SLEEC-PATCH through LEGOS-SLEEC re-analysis.'''
}
def _build_semantic_payload(
    issue_type,
    rules,
    findings,
    repair_operator,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    """
    Build the common input payload used by all LLM semantic repair operators.
    Operator-specific prompt functions decide how this information may be used.
    """
    existing_events = existing_events or []
    existing_measures = existing_measures or []
    existing_responses = existing_responses or []

    return {
        "issue_type": issue_type,
        "repair_operator": repair_operator,
        "sleec_findings": findings,
        "rules": rules,
        "syntax_bank": build_sleec_syntax_bank(rules),
        "system_description": system_description,
        "existing_events": existing_events,
        "existing_measures": existing_measures,
        "existing_responses": existing_responses
    }


def _semantic_common_instructions():
    """
    Rules shared by all six WFI-specific LLM-assisted semantic repair operators.
    """
    return f"""
You are an expert in SLEEC, normative requirements, semantic requirement
refinement, and stakeholder-centered rule repair.

SLEEC-PATCH has already selected the semantic repair operator.

Your task is ONLY to instantiate that selected operator.

Do NOT select another repair operator.

Do NOT generate deterministic repairs such as:
- trigger_refinement
- defeater_introduction
- rule_merging
- rule_removal
- trigger_strengthening
- rule_decomposition

COMMON REQUIREMENTS:

1. Work only on the diagnosed WFI and its supplied diagnosis/witness.

2. Do not rewrite the complete SLEEC specification.

3. Do not modify unrelated rules.

4. Preserve stakeholder intent and the original domain meaning.

5. Use existing declared vocabulary whenever it is sufficient.

6. Every newly introduced semantic element must be grounded in the
   supplied current-use-case evidence.

7. Prefer explicit existing vocabulary whenever possible.

8. system_description may support a new semantic element only when the
   concept is explicit and unambiguous.

9. Diagnosis and witness primarily identify WHY a semantic distinction
   or missing behaviour is required. Do not automatically convert their
   natural-language wording into a new formal event, measure, or response.

10. Do NOT claim grounding from:
    - general knowledge;
    - common sense;
    - an unstated domain assumption;
    - the ALMI worked example;
    - a concept that merely sounds plausible.

11. Do NOT copy ALMI concepts into the current use case unless those
    concepts are independently grounded in the current-use-case input.

12. Populate grounding_evidence for every proposed semantic repair.

13. source_terms must contain exact supporting words, phrases, or formal
    identifiers from the claimed current-use-case source.

14. The proposed patch must directly address the supplied diagnosis and
    witness. A semantically plausible rewrite that leaves the selected
    WFI unchanged is not a successful repair.

15. Preserve diagnosed temporal information. If the affected rule or
    diagnosis contains WITHIN or another temporal constraint, preserve it
    unless the selected semantic repair explicitly requires refinement.

16. Every proposed rule must follow valid SLEEC syntax.

17. Generate only grounded semantic elements supported by the supplied
    current-use-case evidence. Do not invent unsupported vocabulary merely
    to force a candidate repair.

18. Do not decide whether the selected operator is applicable. The repair
    operator has already been selected by SLEEC-PATCH.

19. Do not decide whether the candidate is formally correct. Formal
    correctness is established later by applying the candidate to the
    original SLEEC specification and re-analyzing it with LEGOS-SLEEC.

SLEEC SYNTAX CONTRACT:
{SLEEC_SYNTAX_CONTRACT}

SLEEC SYNTAX EXAMPLES:
{SLEEC_FEW_SHOT_SYNTAX_EXAMPLES}
"""


def event_specialization_prompt(
        issue_type,
        rules,
        findings,
        system_description="",
        existing_events=None,
        existing_measures=None,
        existing_responses=None
    ):
        repair_operator = "event_specialization"

        payload = _build_semantic_payload(
            issue_type=issue_type,
            rules=rules,
            findings=findings,
            repair_operator=repair_operator,
            system_description=system_description,
            existing_events=existing_events,
            existing_measures=existing_measures,
            existing_responses=existing_responses
        )

        return f"""
    {_semantic_common_instructions()}

    SELECTED REPAIR OPERATOR:
    event_specialization

    EVENT SPECIALIZATION:

    The repair operator has already been selected by SLEEC-PATCH.

    Instantiate event_specialization to distinguish partially conflicting
    behaviours associated with different event contexts in the diagnosed WFI.

    Event specialization does NOT require one diagnosed event to be a subtype
    of another diagnosed event.

    For example, two conflicting rules may be triggered by different emergency
    events. Those events establish distinct semantic contexts that may require
    different behaviours. Do not replace one diagnosed trigger event with the
    other merely because both appear in the witness.

    Follow these requirements strictly:

    1. Identify the exact diagnosed rule or rules involved in the supplied
    diagnosis and witness.

    2. Identify the trigger event context whose associated behaviour must be
    made more specific in order to distinguish the partially conflicting
    behaviours.

    3. Use the diagnosis, witness, system description, existing events,
    measures, and responses to determine the semantic distinction required
    by the selected event_specialization operator.

    4. Treat different diagnosed trigger events as evidence of distinct event
    contexts only. Do NOT assume that one diagnosed event is a subtype,
    replacement, or specialization of the other.

    5. Generate only the missing event-specialization element required to
    distinguish the conflicting behaviours.

    6. Any event introduced or used by the repair must be grounded in:
    - existing_events; OR
    - an event explicitly and unambiguously supported by
        system_description.

    7. Prefer existing declared vocabulary whenever it is sufficient.

    8. NEVER invent an event merely by concatenating:
        <existing event> + <diagnosis phrase/context>

    9. Do not convert a measure, Boolean state, response, capability, or
    arbitrary diagnosis phrase into an event merely to instantiate this
    operator.

    10. Preserve the stakeholder intent represented by the diagnosed rules.
        Do not transfer contextual restrictions from one event context to
        another unless the supplied diagnosis or system description explicitly
        supports that transfer.

    11. In particular, a condition associated with one emergency context must
        not automatically be imposed on another emergency context merely
        because the two rules conflict.

    12. Preserve unaffected trigger conditions, temporal constraints, and
        defeaters unless their modification is necessary to express the
        selected event-specialization repair.

    13. Do not replace this operator with defeater introduction, trigger
        refinement, trigger strengthening, measure specialization, capability
        refinement, or new-rule generation.

    14. Do not modify unrelated rules.

    15. The generated candidate must address the supplied diagnosis/witness by
        making the relevant event-triggered behaviours distinguishable.

    16. Before returning the candidate, check:
        - Are the diagnosed rules correctly identified?
        - Are the relevant event contexts grounded?
        - Have you avoided treating two different diagnosed events as if one
        were automatically a subtype of the other?
        - Is every introduced event grounded?
        - Does the candidate distinguish the partially conflicting behaviours?
        - Is stakeholder intent preserved?
        - Are unrelated rules unchanged?
        - Is the proposed rule valid SLEEC syntax?
        - Is the candidate directed at the supplied witness?

    Generate only the semantic/syntactic element required by the selected
    event_specialization operator.

    Do not claim that the generated candidate is formally correct or verified.
    SLEEC-PATCH will apply the candidate to the original specification and
    determine correctness through LEGOS-SLEEC re-analysis.

    OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
    {OPERATOR_EXAMPLES["event_specialization"]}

    Use the ALMI example only to understand the repair pattern.
    Do not copy ALMI vocabulary into another use case.

    CURRENT USE-CASE INPUT:
    {json.dumps(payload, indent=2, ensure_ascii=False)}

    {PATCH_OUTPUT_FORMAT}
    """


def measure_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "measure_specialization"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
measure_specialization

MEASURE SPECIALIZATION:

Instantiate measure_specialization ONLY when the diagnosed WFI depends on
an environmental or contextual measure that is too broad to distinguish
the relevant situations.

Follow these requirements strictly:

1. Identify the exact target rule involved in the diagnosis/witness.

2. Identify the existing measure or contextual predicate that is too broad.

3. Use the diagnosis and witness to determine what environmental/contextual
   distinction is required to eliminate the selected WFI.

4. Search existing_measures and system_description for a grounded,
   more discriminative predicate expressing that distinction.

5. Prefer an already declared measure from existing_measures whenever one
   is sufficient.

6. A specialized measure is permitted only when it is:
   - already present in existing_measures; OR
   - explicitly and unambiguously supported as an environmental/contextual
     predicate by system_description.

7. Do not turn an event, response, capability, or free-text diagnosis phrase
   into a measure merely to make this operator applicable.

8. Do not invent a measure simply because two rules conflict.

9. Preserve the target rule's event, response/action, temporal constraint,
   unrelated conditions, and defeater unless measure specialization itself
   requires changing the selected measure.

10. Do not perform trigger refinement, trigger strengthening,
    defeater introduction, event specialization, capability refinement,
    or new-rule generation instead.

11. The specialized measure must be more discriminative than the existing
    measure and must address the diagnosed contextual distinction.

12. Do not modify unrelated rules.

13. Before returning the patch, check:
    - Is the target rule correct?
    - Is there actually a broad measure requiring specialization?
    - Is the new predicate grounded?
    - Is it actually a measure/context predicate?
    - Is it more discriminative than the existing measure?
    - Are the event and response preserved?
    - Is temporal syntax preserved?
    - Does the proposed change address the witness?

14. Generate only a grounded, more discriminative environmental/contextual
    predicate supported by the supplied current-use-case evidence. Do not
    invent a predicate to force a candidate.

The generated measure is a candidate semantic repair. Its formal correctness
will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["measure_specialization"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""


def capability_refinement_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "capability_refinement"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
capability_refinement

CAPABILITY REFINEMENT:

Instantiate capability_refinement ONLY when the response/action in the
target rule is too broad and the diagnosed WFI requires a grounded,
more-specific system capability.

Follow these requirements strictly:

1. Identify the exact target rule involved in the diagnosis/witness.

2. Identify the broad response/action that requires refinement.

3. Use the diagnosis and witness to determine what response distinction is
   required to eliminate the selected WFI.

4. Search existing_responses and system_description for a grounded,
   more-specific capability expressing that distinction.

5. Prefer an already declared response from existing_responses whenever one
   is sufficient.

6. A refined capability is permitted only when it is:
   - already present in existing_responses; OR
   - explicitly and unambiguously supported as a system capability by
     system_description.

7. Do not create a capability by attaching diagnosis wording to the
   existing response name.

8. Do not convert an event, measure, contextual state, or diagnosis phrase
   into a capability merely to make this operator applicable.

9. Preserve the target rule's trigger, contextual conditions, temporal
   constraint, and defeater unless capability refinement itself requires
   modification of the response.

10. Do not perform event specialization, measure specialization,
    trigger refinement, defeater introduction, or new-rule generation
    instead.

11. The new capability must be semantically more specific than the original
    response and must address the diagnosed behaviour.

12. Do not modify unrelated rules.

13. Before returning the patch, check:
    - Is the target rule correct?
    - Is the original response genuinely too broad?
    - Is the refined capability grounded?
    - Is it actually a system response/capability?
    - Is it more specific than the original response?
    - Is the trigger preserved?
    - Is temporal syntax preserved?
    - Does the proposed change address the witness?

14. Generate only a grounded, more-specific capability supported by the
    supplied current-use-case evidence. Do not invent a capability to force
    a candidate.

The generated capability is a candidate semantic repair. Its formal
correctness will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["capability_refinement"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""


def new_rule_generation_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "new_rule_generation"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
new_rule_generation

NEW-RULE GENERATION:

Instantiate new_rule_generation ONLY when the diagnosis/witness demonstrates
missing normative behaviour that cannot be represented by merely refining an
existing rule.

Follow these requirements strictly:

1. Identify the exact missing normative behaviour demonstrated by the
   diagnosis and witness.

2. Determine the event or trigger required for that missing behaviour.

3. Determine any contextual measures required by the diagnosis.

4. Determine the required system response.

5. Check the existing rules before generating a new rule.
   Do not generate a duplicate or semantically equivalent rule.

6. Every event used in the new rule must be grounded in existing_events or
   explicitly and unambiguously supported as an event by system_description.

7. Every measure/context predicate used in the new rule must be grounded in
   existing_measures or explicitly and unambiguously supported as a measure
   by system_description.

8. Every response used in the new rule must be grounded in existing_responses
   or explicitly and unambiguously supported as a system capability by
   system_description.

9. Diagnosis and witness determine WHAT normative gap must be addressed.
   Do not automatically transform their natural-language wording into new
   formal vocabulary.

10. Prefer composing the new rule from already declared events, measures,
    and responses.

11. Do not invent a new event, measure, or capability merely to make
    new_rule_generation applicable.

12. Generate ONE additional normative rule for the selected missing
    behaviour unless the output contract explicitly requires otherwise.

13. Do not rewrite an existing rule and label it new_rule_generation.

14. Do not introduce deterministic repairs such as defeaters or trigger
    strengthening instead.

15. Preserve any temporal requirement explicitly required by the diagnosis
    or witness.

16. The generated rule must directly prevent or address the supplied witness
    concern.

17. Before returning the patch, check:
    - Does the witness demonstrate missing normative behaviour?
    - Is a genuinely new rule required?
    - Are all events grounded?
    - Are all measures grounded?
    - Is the response grounded?
    - Does an equivalent rule already exist?
    - Is temporal information preserved?
    - Is the new rule valid SLEEC syntax?
    - Does the new rule address the witness?

18. Construct the candidate rule only from grounded semantic elements
    supported by the supplied current-use-case evidence. Do not invent
    unsupported vocabulary or normative behaviour to force a candidate.

The generated rule is a candidate semantic repair. Its formal correctness
will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["new_rule_generation"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""

def redundancy_event_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "redundancy_event_specialization"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

WFI:
Redundancy

WFI DEFINITION:
The diagnosed WFI identifies rules whose behaviours are redundant or
insufficiently distinguishable in the diagnosed situation.

SELECTED REPAIR OPERATOR:
{repair_operator}

OPERATOR DEFINITION:
Resolve the diagnosed redundancy by replacing the relevant event associated
with the redundant behaviour with a new, more distinguishable event.

The new event must give the redundant behaviour a semantically distinct
meaning supported by the current-use-case evidence.

TASK:
1. Identify the exact redundant rule involved in the diagnosis.
2. Identify the event whose meaning must become more distinguishable.
3. Determine the semantic distinction from the diagnosis, witness,
   affected rules, existing vocabulary, or system description.
4. Generate a new event expressing that distinction.
5. Replace only the event required by this operator.
6. Construct the complete candidate SLEEC rule.
7. Generate up to 3 semantically distinct candidates when multiple
   genuinely different evidence-supported distinctions exist.

NEW VOCABULARY:
This operator MAY introduce a new event.

The new event does not need to already occur in existing_events.

However:
- it must have a clear semantic interpretation;
- it must refine or replace an event relevant to the diagnosed redundancy;
- its meaning must be grounded in the supplied current-use-case evidence;
- it must not be an arbitrary concatenation of existing identifiers or
  diagnosis phrases.

Do not introduce a new measure, capability, defeater, or unrelated rule
merely to instantiate this operator.

PRESERVE:
Preserve unaffected conditions, responses, temporal constraints,
defeaters, and unrelated rules.

WORKED EXAMPLE:
Original rules:

r1 when A then B
r2 when C then B

Suppose the supplied use-case evidence establishes that the behaviour
associated with r2 should instead concern a semantically distinct event E.

Candidate repair:

r2 when C then E

E must be supported by the current-use-case evidence.
Do not copy example vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:
Return up to 3 genuinely semantically distinct candidates.
Do not manufacture cosmetic renamings to reach three candidates.

{PATCH_OUTPUT_FORMAT}
"""


def redundancy_measure_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "redundancy_measure_specialization"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

WFI:
Redundancy

WFI DEFINITION:
The diagnosed WFI identifies rules whose behaviours are redundant or
insufficiently distinguishable in the diagnosed situation.

SELECTED REPAIR OPERATOR:
{repair_operator}

OPERATOR DEFINITION:
Resolve the diagnosed redundancy by replacing or refining the relevant
environmental measure with a new, more distinguishable measure.

TASK:
1. Identify the exact redundant rule.
2. Identify the measure requiring differentiation.
3. Examine the diagnosis, witness, affected rules, existing measures,
   and system description.
4. Determine the environmental/contextual distinction required.
5. Generate a new measure expressing that distinction.
6. Replace only the measure required by this operator.
7. Construct the complete candidate SLEEC rule.
8. Generate up to 3 semantically distinct candidates when multiple
   evidence-supported measure distinctions exist.

NEW VOCABULARY:
This operator MAY introduce a new measure.

The new measure does not need to already occur in existing_measures.

It must:
- represent a meaningful environmental/contextual property;
- be grounded in the supplied current-use-case evidence;
- actually be a measure rather than an event, response, or capability.

Do not invent a new measure merely to make two rules syntactically
different.

PRESERVE:
Preserve unaffected events, conditions, responses, temporal constraints,
defeaters, and unrelated rules.

WORKED EXAMPLE:
Original rule:

r1 when A and c then B

If the evidence establishes that d is the more precise environmental
distinction required for this behaviour:

r1 when A and d then B

The example demonstrates the transformation pattern only.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:
Return up to 3 genuinely semantically distinct candidates.

{PATCH_OUTPUT_FORMAT}
"""


def concern_new_rule_generation_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "concern_new_rule_generation"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

WFI:
Concern / Insufficiency

WFI DEFINITION:
A concern identifies behaviour that is insufficiently addressed by the
current normative specification. The diagnosed situation exposes missing
normative behaviour.

SELECTED REPAIR OPERATOR:
{repair_operator}

OPERATOR DEFINITION:
Address the diagnosed concern by generating an additional normative rule
that specifies the missing behaviour required for the diagnosed situation.

TASK:
1. Read the diagnosed concern and witness.
2. Determine the behaviour missing from the specification.
3. Examine existing rules to avoid generating a duplicate.
4. Generate an additional rule directly addressing the concern.
5. Preserve relevant contextual conditions supplied by the diagnosis.
6. Generate up to 3 semantically distinct candidate rules when the
   supplied evidence supports genuinely different ways of addressing
   the same concern.

NEW VOCABULARY:
This operator MAY create a new rule.

It MAY introduce a new event when that event is necessary to express the
missing behaviour and is clearly grounded in the supplied current-use-case
evidence.

Prefer existing events, measures, and responses when they already express
the required behaviour.

Do not invent a new concept merely to make candidates different.

PRESERVE:
Do not rewrite or remove unrelated existing rules.
Do not silently convert this operation into trigger refinement,
defeater introduction, rule decomposition, or another operator.

WORKED EXAMPLE:
Concern:

when HumanOnFloor and
({{userOccupied}} and ({{riskLevel}} = high))
then not CallEmergencyServices

Concern is raised.

Candidate additional rule:

R_new when HumanOnFloor and
          ({{userOccupied}} and ({{riskLevel}} = high))
      then CallEmergencyServices

The example demonstrates the new-rule-generation pattern only.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:
Return up to 3 genuinely semantically distinct new-rule candidates.
Each candidate must independently address the same diagnosed concern.

{PATCH_OUTPUT_FORMAT}
"""


def purpose_capability_refinement_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "purpose_capability_refinement"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

WFI:
Purpose Blocking / Restrictiveness

WFI DEFINITION:
A purpose-blocking WFI occurs when an existing normative rule obstructs
an intended system purpose in the diagnosed situation.

SELECTED REPAIR OPERATOR:
{repair_operator}

OPERATOR DEFINITION:
Refine a broad system response/capability into a more specific capability
when the diagnosed purpose-blocking WFI shows that the existing response
is too broad for the intended behaviour.

This follows the capability-refinement principle used by SLEEC-PATCH:
- identify the response/action that is too broad;
- refine that response into a more specific system capability;
- preserve the rest of the affected rule unless changing it is required
  by the selected capability refinement.

TASK:
1. Identify the exact rule involved in the diagnosed purpose blocking.

2. Identify the response/action whose current meaning is too broad for
   the intended purpose.

3. Use the diagnosed purpose, witness, affected rules, existing vocabulary,
   and system description to determine the required response distinction.

4. Generate a more specific system capability or response expressing that
   distinction.

5. Modify only the response/capability required by this operator.

6. Preserve the trigger, contextual conditions, temporal constraint, and
   existing defeaters unless the capability refinement itself requires
   otherwise.

7. Generate up to 3 genuinely semantically distinct candidates only when
   the supplied evidence supports different capability refinements.

GROUNDING:
The refined capability must be grounded in the CURRENT use case.

Prefer a capability already present in existing_responses when it expresses
the required distinction.

A new capability may be introduced only when its meaning is explicitly and
unambiguously supported by at least one of:
- the system description;
- the diagnosed purpose;
- the diagnosis/witness;
- the affected rules or existing current-use-case vocabulary.

Do not invent a capability merely because it sounds plausible.

Do not create a new capability simply by attaching diagnosis wording,
purpose wording, or contextual words to the original response name.

The diagnosis and witness identify WHY refinement is required. They do not,
by themselves, justify arbitrary new functionality.

PRESERVE:
- stakeholder intent;
- the original domain meaning;
- the affected rule's trigger;
- relevant contextual conditions;
- temporal constraints;
- existing defeaters;
- unrelated rules.

Do NOT solve the WFI by:
- introducing a purpose defeater;
- trigger refinement;
- trigger strengthening;
- rule decomposition;
- rule removal;
- adding an unrelated new rule.

Those are different repair operators.

OPERATOR-SPECIFIC WORKED EXAMPLE:

EXAMPLE: CAPABILITY REFINEMENT FOR RESTRICTIVENESS

Blocking rule:

    r1 when HumanOnFloor and not humanAssents
       then not CallEmergencyServices within 500 seconds

Intended purpose:

    when HumanOnFloor and UserUnconscious and not humanAssents
    then CallEmergencyServices within 4 minutes

Selected operator:

    capability_refinement

Candidate capability refinement:

    r1 when HumanOnFloor and not humanAssents
       then not RequestUrgentCareAssessment within 500 seconds

In this example, the broad emergency-response capability
CallEmergencyServices is refined into the more specific
RequestUrgentCareAssessment capability.

Notice what the repair preserves:
- the original trigger HumanOnFloor;
- the contextual condition not humanAssents;
- the negative response form;
- the temporal bound within 500 seconds.

Only the capability required by capability refinement is changed.

IMPORTANT:
This example demonstrates the capability-refinement repair pattern only.

Do NOT copy HumanOnFloor, humanAssents, CallEmergencyServices,
RequestUrgentCareAssessment, or any other ALMI-specific concept into
another use case unless that concept is independently grounded in the
CURRENT use-case evidence.

For the current use case, derive the refined capability from the supplied
purpose, diagnosis/witness, system description, affected rules, and
current-use-case vocabulary.

IMPORTANT:
The generated result is only a candidate repair.

Do not claim that it resolves the purpose-blocking WFI.
Do not claim that it introduces no new WFIs.

SLEEC-PATCH will apply the candidate to the original specification and
LEGOS-SLEEC re-analysis will determine whether the targeted WFI is
eliminated without unacceptable regression.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:
Return up to 3 genuinely semantically distinct capability refinements.
Do not manufacture cosmetic renamings merely to produce three candidates.

{PATCH_OUTPUT_FORMAT}
"""


def conflict_event_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "conflict_event_specialization"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

WFI:
Situational Conflict

WFI DEFINITION:
A situational conflict occurs when individually meaningful rules produce
conflicting or partially conflicting behaviours in a particular diagnosed
situation.

SELECTED REPAIR OPERATOR:
{repair_operator}

OPERATOR DEFINITION:
Resolve the diagnosed situational conflict by introducing an intermediary
or more distinguishable event that separates the conflicting or
semi-conflicting behaviours.

Co-occurrence of events in a witness does NOT by itself establish that
one event is a specialization, subtype, or component of another.

TASK:
1. Identify the exact conflicting rules.
2. Identify the behaviour/event requiring differentiation.
3. Use the witness to understand why the behaviours conflict.
4. Determine the semantic distinction required to separate them.
5. Generate an intermediary or more distinguishable event expressing
   that distinction.
6. Modify only the component required by this event-specialization repair.
7. Generate up to 3 semantically distinct candidates when multiple
   evidence-supported event distinctions exist.

NEW VOCABULARY:
This operator MAY introduce a new event.

The new event does not need to already occur in existing_events.

It must have a clear semantic interpretation supported by the diagnosed
conflict, witness, affected rules, system description, or declared
current-use-case vocabulary.

IMPORTANT:
If a witness contains:

SmokeDetectorAlarm
HumanOnFloor

do NOT automatically construct:

SmokeDetectorAlarmWhileHumanOnFloor
SmokeDetectorAlarmWithHumanOnFloor
HumanOnFloorFireEmergency

The simultaneous occurrence of two events is not sufficient semantic
grounding for a combined event.

Do not transfer a condition associated with one event context to another
merely because their rules conflict.

WORKED EXAMPLE:
r1 when SmokeDetectorAlarm
   then CallingFireMan within 5 minutes

r2 when HumanOnFloor and not humanAssents
   then not CallEmergencyServices within 500 seconds

The witness may contain both events.

This does NOT establish SmokeDetectorAlarmWithHumanOnFloor as a valid
specialized event.

A valid new event requires an independently meaningful distinction
supported by the current-use-case evidence.

If no meaningful event can be justified, do not invent one merely to
create another candidate.

PRESERVE:
Preserve unaffected conditions, intended responses, temporal constraints,
defeaters, and unrelated rules.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:
Return up to 3 genuinely semantically distinct candidates.
Do not generate cosmetic event-name variants.

{PATCH_OUTPUT_FORMAT}
"""


def conflict_measure_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "conflict_measure_specialization"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

WFI:
Situational Conflict

WFI DEFINITION:
A situational conflict occurs when individually meaningful rules produce
conflicting or partially conflicting behaviours under a particular
environmental or contextual situation identified by the diagnosis and
witness.

SELECTED REPAIR OPERATOR:
{repair_operator}

OPERATOR DEFINITION:
Resolve the diagnosed situational conflict by introducing a new, more
distinguishable environmental measure that separates the conflicting
contexts.

TASK:
1. Identify the exact conflicting rules.
2. Identify the environmental measure or contextual state relevant to
   the conflict.
3. Examine the measure values present when the conflict is triggered.
4. Determine the environmental distinction required to separate the
   conflicting behaviours.
5. Generate a new, more distinguishable measure representing that
   distinction.
6. Modify only the measure component required by this operator.
7. Generate up to 3 candidates when multiple genuinely different,
   evidence-supported environmental distinctions exist.

NEW VOCABULARY:
This operator MAY introduce a new measure.

The measure does not need to already occur in existing_measures.

It must:
- represent a meaningful environmental/contextual property;
- be supported by the diagnosis, witness, affected rules, system
  description, or declared vocabulary;
- actually be a measure rather than an event, response, or capability.

Do not invent a measure solely because a different name would make the
rules syntactically different.

WORKED EXAMPLE FROM ALMI:

Original conflicting rules:

r4 when SmokeDetectorAlarm and not humanConfirm
   then CallEmergencyServices within 5 minutes

r5 when HumanOnFloor and not humanConfirm
   then not CallEmergencyServices within 500 seconds

The shared contextual measure humanConfirm does not sufficiently
distinguish the conflicting situations.

Example candidate 1:

r4 when SmokeDetectorAlarm and not humanConfirm
   then CallEmergencyServices within 5 minutes

r5 when HumanOnFloor and not humanAssent
   then not CallEmergencyServices within 500 seconds

Example candidate 2:

r4 when SmokeDetectorAlarm and not humanConscious
   then CallEmergencyServices within 5 minutes

r5 when HumanOnFloor and not humanConfirm
   then not CallEmergencyServices within 500 seconds

IMPORTANT:
These examples demonstrate the repair pattern only.

humanAssent and humanConscious may be used in another use case only
when independently grounded in that current use case.

Do not invent a measure merely to distinguish two rules.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:
Return up to 3 genuinely semantically distinct candidates.
Do not manufacture measure-name variants.

{PATCH_OUTPUT_FORMAT}
"""
def semantic_rule_merging_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "semantic_rule_merging"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

WFI:
Situational Conflict

WFI DEFINITION:
A situational conflict occurs when individually meaningful rules can become
applicable in a diagnosed situation while requiring conflicting or partially
conflicting behaviours.

SELECTED REPAIR OPERATOR:
{repair_operator}

OPERATOR DEFINITION:
Semantically merge the rules identified by LEGOS-SLEEC as participating
in the diagnosed situational conflict when deterministic rule_merging is
not applicable.

The purpose of this operator is NOT to discover new conflicting rules.
The conflicting rules have already been identified by LEGOS-SLEEC.

TASK:
1. Identify the exact rules supplied in the diagnosed situational conflict.
2. Use only those diagnosed rules as the rules to be merged.
3. Examine their triggers, responses, defeaters, temporal constraints,
   diagnosis, and witness.
4. Determine a semantically meaningful way to represent their intended
   behaviours in a merged SLEEC rule.
5. Preserve the intent of both diagnosed rules.
6. Use the diagnosed witness and system description only as semantic
   grounding for the merge.
7. Generate up to 3 semantically distinct merged-rule candidates.

IMPORTANT CONSTRAINTS:
- Do NOT select unrelated rules from the specification.
- Do NOT claim that a candidate resolves the conflict.
- Do NOT claim that a candidate is verified.
- Do NOT remove behaviour merely to make the conflict disappear.
- Do NOT invent unsupported system semantics.
- Preserve relevant temporal constraints.
- Preserve relevant defeater behaviour unless the proposed merge explicitly
  and meaningfully represents that behaviour.
- Do not generate cosmetic variants of the same merged rule.
- Every candidate must represent a genuine semantic alternative.
SLEEC SYNTAX CONTRACT:
Every proposed merged rule MUST be syntactically valid SLEEC.

- Do NOT combine alternative trigger events using "or".
  INVALID:
      when EventA or EventB then Response

- Event triggers may be combined only using structures already supported
  by the supplied SLEEC specification.

- Boolean "or" may be used only inside supported measure expressions,
  for example:
      ({{measureA}} or {{measureB}})
  when that syntax is already supported by the specification.

- Do NOT invent new SLEEC syntax, operators, keywords, or rule forms.

- Use only events, measures, responses, constants, and temporal units
  grounded in CURRENT USE-CASE INPUT.

- A semantic merge must reconcile the diagnosed rules; merely placing
  their trigger events on opposite sides of "or" is NOT a semantic merge.

- Preserve the distinct semantics of the diagnosed rules. If the rules
  have different defeaters, alternative responses, or temporal bounds,
  explicitly reason about those differences when constructing the
  candidate.

- If a temporal constraint from a diagnosed rule remains relevant to the
  behaviour represented by the merged candidate, preserve it on the
  corresponding response. Do NOT arbitrarily transfer that temporal
  constraint to behaviour originating from another rule.

- The proposed_rule MUST be directly parseable as a SLEEC rule without
  requiring a later syntax-repair step.

- If no meaningful merged rule can be expressed using the existing SLEEC
  grammar and grounded vocabulary, return no candidate instead of
  inventing syntax.
DETERMINISTIC FALLBACK RELATION:
This operator is intended for diagnosed situational conflicts for which
deterministic rule_merging is not structurally applicable.

It must not simply reproduce a deterministic rule_merging candidate.

VERIFICATION:
The generated rules are CANDIDATE PATCHES ONLY.

SLEEC-PATCH will independently:
1. apply each candidate to the complete SLEEC specification;
2. rerun LEGOS-SLEEC;
3. determine whether the original target situational conflict is removed;
4. detect whether the candidate introduces other WFIs.

A candidate must therefore never describe itself as successful, correct,
safe, or verified.

PRESERVE:
Preserve unaffected rules, intended behaviours, relevant conditions,
temporal constraints, and system semantics.

CURRENT USE-CASE INPUT:

{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:

Return up to 3 genuinely semantically distinct rule-merging candidates.

Do not manufacture cosmetic rule variants.
Do not return the same semantic merge with only wording, formatting,
parentheses, or rule-ID differences.

If the supplied evidence does not support a meaningful semantic merge,
return no candidate rather than inventing one.

{PATCH_OUTPUT_FORMAT}

"""

def build_prompt(
    issue_type,
    rules,
    findings,
    repair_operator,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
    ):
    prompt_builders = {
    "redundancy_event_specialization":
        redundancy_event_specialization_prompt,

    "redundancy_measure_specialization":
        redundancy_measure_specialization_prompt,

    "concern_new_rule_generation":
        concern_new_rule_generation_prompt,

    "purpose_capability_refinement":
        purpose_capability_refinement_prompt,

    "conflict_event_specialization":
        conflict_event_specialization_prompt,

    "conflict_measure_specialization":
        conflict_measure_specialization_prompt,
    "semantic_rule_merging":
        semantic_rule_merging_prompt,    
   }

    if repair_operator not in LLM_SEMANTIC_OPERATORS:
        raise ValueError(
            f"{repair_operator} is deterministic and must be generated "
            f"by Python script, not GPT."
        )

    builder = prompt_builders.get(repair_operator)

    if builder is None:
        raise ValueError(
            f"No prompt builder is registered for LLM semantic operator: "
            f"{repair_operator}"
        )

    return builder(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )


# PATCH RANKING — Section C
def patch_quality_ranking_prompt(
    patch,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    payload = {
        "system_description": system_description,
        "original_rule": patch.get("original_rule", ""),
        "proposed_rule": patch.get("proposed_rule", ""),
        "operation": patch.get("operation", ""),
        "natural_language_explanation": patch.get(
            "natural_language_explanation", patch.get("explanation", "")
        ),
        "missing_element": patch.get("missing_element", ""),
        "issue_type": patch.get("issue_type", ""),
        "selected_issue": patch.get("selected_issue", ""),
        "affected_rules": patch.get("affected_rules", []),
        "diagnosis_context": patch.get("diagnosis_context", ""),
        "existing_events": existing_events or [],
        "existing_measures": existing_measures or [],
        "existing_responses": existing_responses or []
    }

    return f"""
The SLEEC repair below has ALREADY passed formal verification.
Do NOT assess formal correctness and do NOT propose a different repair.

Assess only:

SEMANTIC CLARITY (0-100)
Prefer specific, unambiguous, domain-grounded events, measures, and responses.

VOCABULARY INTERPRETATION RULES:
- existing_events, existing_measures, and existing_responses contain concepts
  already declared or already used in the current SLEEC specification.
- Do NOT classify or penalize a concept as newly introduced merely because it
  is absent from the individual original_rule.
- A concept is genuinely new only if it appears in proposed_rule but is absent
  from existing_events, existing_measures, existing_responses, and original_rule.
- Reuse of a declared concept should normally support semantic clarity when the
  concept is used consistently with its domain meaning.
- For a genuinely new concept, assess whether it is specific, unambiguous,
  domain-grounded, explained by the repair rationale/system description, and
  meaningfully distinct from existing vocabulary.
- Penalize genuinely new generic placeholders such as RiskHigh, ConditionMet,
  SituationBad, UserIsOk, NormalState, and SpecialCase.
- Do NOT penalize declared concepts such as riskLevel, userOccupied,
  humanAssents, SmokeDetectorAlarm, or userDisablesAlarm when they appear in
  the supplied existing vocabulary.

INTERPRETABILITY (0-100)
Prefer preservation of apparent stakeholder intent, an understandable rationale,
minimal dependence on unstated context, and descriptive predicates.
Penalize unexplained action changes or contextual distinctions.

AND, OR, NOT, WHEN, THEN, UNLESS, and WITHIN are SLEEC syntax, not predicates.
If proposed_rule contains multiple rules, assess the complete repair.

INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

Return ONLY this raw JSON object:
{{
  "semantic_clarity": 0,
  "semantic_clarity_reason": "one concise reason",
  "interpretability": 0,
  "interpretability_reason": "one concise reason"
}}
"""
