import json
import re


PATCH_OUTPUT_FORMAT = """
Return ONLY a raw JSON array.

The repair operator has already been selected by SLEEC-PATCH.

Your task is to instantiate that selected operator and generate the
missing semantic/syntactic element required by it.

Each candidate patch MUST use this structure:

[
  {
    "patch_id": "p1",
    "issue_type": "<diagnosed issue type>",
    "operation": "<selected repair operator>",

    "target_rule_id": "<target rule id, or empty only when the selected operator creates a new rule>",
    "original_rule": "<exact original SLEEC rule, or empty only when the selected operator creates a new rule>",

    "target_element": "<event|measure|response|new_rule>",
    "missing_element": "<the semantic/syntactic element generated by the selected operator>",
    "proposed_rule": "<complete candidate SLEEC rule containing the generated element>",

    "grounding_evidence": {
      "source": "<system_description|diagnosis|witness|existing_vocabulary>",
      "source_terms": [
        "<exact supporting term or formal identifier from the claimed source>"
      ],
      "existing_element": "<existing element being specialized/refined, or empty for new-rule generation when appropriate>",
      "new_element": "<the generated semantic/syntactic element>",
      "relationship": "<how the cited evidence supports the generated element>"
    },

    "natural_language_explanation": "<brief explanation of how the generated element instantiates the selected repair operator for the diagnosed WFI>",

    "modification_cost": 1,
    "new_events_added": 0,
    "new_measures_added": 0,
    "new_responses_added": 0,
    "new_rules_added": 0,
    "defeaters_added": 0
  }
]

IMPORTANT:

- The selected repair operator is fixed. Do not choose another operator.
- Generate only the semantic/syntactic element required by that operator.
- Do not claim that the candidate is formally correct or verified.
- Do not claim that the targeted WFI has been eliminated.
- Do not claim that the candidate introduces no additional WFIs.
- Formal correctness is determined later by SLEEC-PATCH through
  LEGOS-SLEEC re-analysis.
- Do not modify unrelated rules.
- Set the *_added fields according to the actual candidate repair.
- Do NOT use markdown.
- Do NOT use ```json.
- Do NOT add text before or after the JSON.
- The response MUST start with [ and end with ].
"""


LLM_SEMANTIC_OPERATORS = [
    "event_specialization",
    "measure_specialization",
    "response_refinement",
    "new_rule_generation",
]


def build_sleec_syntax_bank(rules):
    rules = rules or []
    rule_texts = [
        str(rule.get("raw") or rule.get("text") or "").strip()
        if isinstance(rule, dict)
        else str(rule or "").strip()
        for rule in rules
    ]
    rule_texts = [text for text in rule_texts if text]

    observed = []
    if any(" unless " in text.lower() for text in rule_texts):
        observed.append("unless exceptions with optional alternative responses")
    if any(" within " in text.lower() for text in rule_texts):
        observed.append("within time bounds")
    if any(re.search(r"\{[A-Za-z_][A-Za-z0-9_]*\}", text) for text in rule_texts):
        observed.append("boolean measures wrapped in braces")
    if any(re.search(r"\{?[A-Za-z_][A-Za-z0-9_]*\}?\s*[<>=]\s*[A-Za-z0-9_]+", text) for text in rule_texts):
        observed.append("measure comparisons")
    if any(re.search(r"\b(?:and|or|not)\b", text, flags=re.IGNORECASE) for text in rule_texts):
        observed.append("and/or/not logical conditions")

    examples = rule_texts[:5]

    return {
        "allowed_rule_templates": [
            "RuleName when Trigger then Action",
            "RuleName when Trigger and Condition then Action",
            "RuleName when Trigger then Action within Number seconds",
            "RuleName when Trigger then Action unless Condition",
            "RuleName when Trigger then Action unless Condition then AlternativeAction",
        ],
        "observed_syntax_features": observed,
        "local_rule_examples": examples,
        "instruction": (
            "Use only these observed SLEEC syntax forms and the supplied "
            "vocabulary. Do not invent grammar constructs."
        )
    }


SLEEC_SYNTAX_CONTRACT = """
SLEEC SYNTAX CONTRACT:
Use only the SLEEC syntax already present in the input specification.

Allowed declaration lines:
- event EventName
- measure measureName:boolean
- measure measureName:numeric
- constant ConstantName = value

Allowed rule shapes:
- RuleName when Trigger then Action
- RuleName when Trigger and Condition then Action
- RuleName when Trigger then Action within Number seconds
- RuleName when Trigger then Action
       unless Condition then AlternativeAction
- RuleName when Trigger then Action
       unless Condition

Allowed condition syntax:
- "and" may combine trigger events and supported conditions.
- "not" may negate supported boolean conditions.
- "or" is allowed only inside supported condition/measure expressions;
  it must NOT be used to combine alternative trigger events.
- parentheses for grouping supported condition/measure expressions
- boolean measures as {measureName}
- numeric comparisons such as {measureName} > ConstantName

IMPORTANT EVENT-TRIGGER RESTRICTION:
- A SLEEC rule has exactly ONE trigger event immediately after "when".

- After the trigger event, "and" may introduce only a supported
  condition/measure expression. It must NOT introduce another event.

- Do NOT write:
      when EventA or EventB then Action

- Do NOT write:
      when EventA and EventB then Action

- VALID shapes include:
      when EventA then Action
      when EventA and {{measureA}} then Action
      when EventA and (not {{measureA}}) then Action
      when EventA and ({{measureA}} or {{measureB}}) then Action

- INVALID shapes include:
      when EventA or EventB then Action
      when EventA and EventB then Action

- Event names are NOT boolean conditions and must not be placed after
  "and", "or", or "not" as if they were measures.

- Alternative trigger events cannot be combined into one trigger using
  either "and" or "or".

- If a repair requires combining two different trigger events and no
  equivalent repair can be expressed using one existing trigger event
  plus grounded measure conditions, defeaters, responses, or temporal
  constraints, do NOT invent a merged rule. Return no candidate.

Forbidden syntax:
- Do not use IF, ELSE, REQUIRES, BECAUSE, SHOULD, MUST, UNTIL, EXCEPT, IMPLIES, or arrows.
- Do not invent new SLEEC keywords.
- Do not put prose, bullet points, or comments inside proposed_rule.
- Do not wrap the whole rule in parentheses.
- Do not output def_start, def_end, rule_start, or rule_end inside proposed_rule.
- Do not output declaration lines inside proposed_rule.

Vocabulary accounting:
- If missing_element is a new event, set new_events_added to 1.
- If missing_element is a new measure, set new_measures_added to 1.
- If missing_element is a new response, set new_responses_added to 1.
- If the patch adds a new rule, set new_rules_added to 1.
- Otherwise the corresponding counter must be 0.

The generated candidate must follow this syntax contract exactly.
Do not invent new SLEEC syntax to express the selected repair operator.
"""


SLEEC_FEW_SHOT_SYNTAX_EXAMPLES = """
FEW-SHOT SLEEC SYNTAX EXAMPLES:
These examples teach syntax shape only. Do not copy their domain vocabulary.

Example 1: edit an existing event trigger
Original rule:
r1 when BroadEvent then SafeAction
Correct proposed_rule:
r1 when SpecificEvent then SafeAction

Example 2: preserve an unless branch
Original rule:
r2 when RequestAction then DoAction
   unless {unsafeState} then StopAction
Correct proposed_rule:
r2 when SpecificRequestAction then DoAction
   unless {unsafeState} then StopAction

Example 3: preserve temporal syntax
Original rule:
r3 when EmergencyEvent then NotifyHuman within 60 seconds
Correct proposed_rule:
r3 when SpecificEmergencyEvent then NotifyHuman within 60 seconds

Example 4: add one new rule
Correct proposed_rule:
r_new when MissingConditionEvent and {relevantState} then RequiredAction

"""



OPERATOR_EXAMPLES = {

'event_specialization': '''EXAMPLE: EVENT SPECIALIZATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
Different emergency events may require different responses.
A fire-related emergency and a human-on-floor emergency must not
automatically be treated as the same situation.

Original conflicting rules:

r1 when SmokeDetectorAlarm
   then CallEmergencyServices within 5 minutes

r2 when HumanOnFloor and not humanAssents
   then not CallEmergencyServices within 500 seconds

Diagnosis:
A witness shows that a smoke alarm can occur while a human is on the floor
without assent. The two rules can therefore become applicable while requiring
conflicting behaviour concerning CallEmergencyServices.

Selected operator:
event_specialization

Semantic distinction:
SmokeDetectorAlarm and HumanOnFloor represent different event contexts.

The purpose of event specialization is to distinguish the partially
conflicting behaviours associated with these event contexts.

Do NOT interpret SmokeDetectorAlarm as a specialization of HumanOnFloor.
Do NOT interpret HumanOnFloor as a specialization of SmokeDetectorAlarm.

The diagnosed events establish the event contexts that must be
distinguished; one event must not simply replace the other.

Grounded repair pattern:

If the supplied ALMI vocabulary and system description support a
fire-specific response such as CallingFireMan, the behaviour associated
with SmokeDetectorAlarm may be specialized:

r1 when SmokeDetectorAlarm
   then CallingFireMan within 5 minutes

while the HumanOnFloor rule remains associated with its own emergency
context.

This distinguishes the fire-related behaviour from the human-on-floor
emergency behaviour instead of imposing the human-assent condition on
the fire-related event.

IMPORTANT:

Do NOT generate:

SmokeDetectorAlarmWithoutHumanAssent
SmokeDetectorAlarmWhileHumanOnFloor
HumanOnFloorFireEmergency

merely by combining existing event names with diagnosis text.

Do NOT infer that CallingFireMan requires human assent merely because
humanAssents occurs in the HumanOnFloor rule.

Do NOT transfer contextual restrictions from one diagnosed event context
to another unless the supplied diagnosis, witness, or system description
explicitly supports that transfer.

Use only events and responses grounded in the supplied current-use-case
vocabulary or system description.

Preserve unaffected temporal constraints, contextual conditions, and
defeaters.

Modify only the behaviour necessary to instantiate the selected
event_specialization operator.

The generated candidate is not assumed to be formally correct.
SLEEC-PATCH will apply it to the original specification and use
LEGOS-SLEEC re-analysis to determine whether the diagnosed WFI is
eliminated without introducing additional WFIs.''',

'measure_specialization': '''EXAMPLE: MEASURE SPECIALIZATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:

r4 when SmokeDetectorAlarm and not humanConfirm
   then CallEmergencyServices within 5 minutes

r5 when HumanOnFloor and not humanConfirm
   then not CallEmergencyServices within 500 seconds

Diagnosis:
Both behaviours contain contextual information represented by
humanConfirm. The diagnosed conflict requires a more discriminative
environmental/contextual distinction.

Selected operator:
measure_specialization

Generation task:
Use the diagnosis and witness to determine what environmental/contextual
distinction is required.

Generate only the grounded, more discriminative measure required by the
selected operator.

Search existing_measures first. A new measure may be generated from the
system description only when the environmental/contextual concept is
explicitly and unambiguously supported there.

For example, ALMI may contain distinctions involving concepts such as:

humanAssent

or:

humanConscious

These concepts must NOT be introduced merely because they appear useful.
They may be used only when grounded in the supplied current-use-case input.

The diagnosis and witness identify WHY measure specialization is required.
Their natural-language wording must not automatically be converted into
a new measure.

Preserve:
- the relevant event;
- the response;
- the temporal constraint;
- unrelated conditions; and
- defeaters.

Do NOT invent an environmental predicate merely to force a candidate.''',


'response_refinement': '''EXAMPLE: RESPONSE REFINEMENT — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
The specification contains emergency-related responses such as:

CallingFireMan

and:

CallEmergencyServices

These responses represent different system capabilities and must not
automatically be treated as interchangeable.

Example rule:

r1 when SmokeDetectorAlarm
   then CallEmergencyServices within 5 minutes

Diagnosis:
The diagnosed behaviour requires a different, more appropriate response
supported by the current-use-case evidence.

Selected operator:
response_refinement

Generation task:
Use the diagnosis and witness to determine what response distinction is
required.

Generate only the grounded response required by the selected operator.

Search existing_responses first. A response corresponding to a system
capability may be generated from the system description only when that
capability is explicitly and unambiguously supported there.

For example, if the supplied current-use-case evidence establishes
CallingFireMan as the appropriate response for the diagnosed fire-related
behaviour, it may be used as the refined response.

Do NOT invent capabilities such as:

CallSpecialEmergencyServices
CallEmergencyServicesForFire
CallEmergencyServicesForUnconsciousHuman

unless those capabilities are explicitly supported by the supplied
current-use-case evidence.

The diagnosis and witness identify WHY response refinement is required.
Their natural-language wording must not automatically be converted into
a new response or capability.

Preserve:
- the trigger;
- contextual conditions;
- the temporal constraint; and
- defeaters.

Change only the response required by response_refinement.''',


'new_rule_generation': '''EXAMPLE: NEW RULE GENERATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
The specification contains emergency situations such as:

HumanOnFloor

and system responses such as:

CallEmergencyServices

Diagnosis:
A LEGOS-SLEEC witness identifies missing normative behaviour involving
HumanOnFloor that must be addressed by an additional rule.

Selected operator:
new_rule_generation

Generation task:
Use the diagnosed rules, witness, diagnosis, system description, and
existing vocabulary to identify the missing normative behaviour.

Generate only the additional normative rule required by the selected
operator.

Every element used in the generated rule must be grounded:
- events in existing_events or explicitly supported by system_description;
- measures in existing_measures or explicitly supported by system_description;
- responses in existing_responses or explicitly supported by system_description.

Grounded structural pattern:

If the supplied diagnosis, witness, existing vocabulary, and ALMI system
description establish that HumanOnFloor requires CallEmergencyServices,
the following form illustrates the operator:

r_new when HumanOnFloor
      then CallEmergencyServices

This is a structural example only.
The current-use-case evidence must justify the generated normative behaviour.

Do NOT invent unsupported responses such as:

CallDoctor

and do NOT invent contextual predicates such as:

{patientCritical}
{hospitalAvailable}
{familyPermission}

unless those concepts are explicitly grounded in the supplied
current-use-case evidence.

Do not create unnecessary new events, measures, or capabilities.

The generated rule must directly address the diagnosed witness concern
and must not duplicate an existing rule.

Formal correctness of the generated candidate is determined later by
SLEEC-PATCH through LEGOS-SLEEC re-analysis.'''
}
def _build_semantic_payload(
    issue_type,
    rules,
    findings,
    repair_operator,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    """
    Build the common input payload used by all LLM semantic repair operators.
    Operator-specific prompt functions decide how this information may be used.
    """
    existing_events = existing_events or []
    existing_measures = existing_measures or []
    existing_responses = existing_responses or []

    return {
        "issue_type": issue_type,
        "repair_operator": repair_operator,
        "sleec_findings": findings,
        "rules": rules,
        "syntax_bank": build_sleec_syntax_bank(rules),
        "system_description": system_description,
        "existing_events": existing_events,
        "existing_measures": existing_measures,
        "existing_responses": existing_responses
    }


def _semantic_common_instructions():
    """
    Rules shared by all six WFI-specific LLM-assisted semantic repair operators.
    """
    return f"""
You are an expert in SLEEC, normative requirements, semantic requirement
refinement, and stakeholder-centered rule repair.

SLEEC-PATCH has already selected the semantic repair operator.

Your task is ONLY to instantiate that selected operator.

Do NOT select another repair operator.

Do NOT generate deterministic repairs such as:
- trigger_refinement
- defeater_introduction
- rule_merging
- rule_removal
- trigger_strengthening
- rule_decomposition

COMMON REQUIREMENTS:

1. Work only on the diagnosed WFI and its supplied diagnosis/witness.

2. Do not rewrite the complete SLEEC specification.

3. Do not modify unrelated rules.

4. Preserve stakeholder intent and the original domain meaning.

5. Use existing declared vocabulary whenever it is sufficient.

6. Every newly introduced semantic element must be grounded in the
   supplied current-use-case evidence.

7. Prefer explicit existing vocabulary whenever possible.

8. system_description may support a new semantic element only when the
   concept is explicit and unambiguous.

9. Diagnosis and witness primarily identify WHY a semantic distinction
   or missing behaviour is required. Do not automatically convert their
   natural-language wording into a new formal event, measure, or response.

10. Do NOT claim grounding from:
    - general knowledge;
    - common sense;
    - an unstated domain assumption;
    - the ALMI worked example;
    - a concept that merely sounds plausible.

11. Do NOT copy ALMI concepts into the current use case unless those
    concepts are independently grounded in the current-use-case input.

12. Populate grounding_evidence for every proposed semantic repair.

13. source_terms must contain exact supporting words, phrases, or formal
    identifiers from the claimed current-use-case source.

14. The proposed patch must directly address the supplied diagnosis and
    witness. A semantically plausible rewrite that leaves the selected
    WFI unchanged is not a successful repair.

15. Preserve diagnosed temporal information. If the affected rule or
    diagnosis contains WITHIN or another temporal constraint, preserve it
    unless the selected semantic repair explicitly requires refinement.

16. Every proposed rule must follow valid SLEEC syntax.

17. Generate only grounded semantic elements supported by the supplied
    current-use-case evidence. Do not invent unsupported vocabulary merely
    to force a candidate repair.

18. Do not decide whether the selected operator is applicable. The repair
    operator has already been selected by SLEEC-PATCH.

19. Do not decide whether the candidate is formally correct. Formal
    correctness is established later by applying the candidate to the
    original SLEEC specification and re-analyzing it with LEGOS-SLEEC.

SLEEC SYNTAX CONTRACT:
{SLEEC_SYNTAX_CONTRACT}

SLEEC SYNTAX EXAMPLES:
{SLEEC_FEW_SHOT_SYNTAX_EXAMPLES}
"""


def event_specialization_prompt(
        issue_type,
        rules,
        findings,
        system_description="",
        existing_events=None,
        existing_measures=None,
        existing_responses=None
    ):
        repair_operator = "event_specialization"

        normalized_issue = str(issue_type or "").strip().lower()

        if normalized_issue in {
            "conflict",
            "conflicts",
            "situational_conflict",
            "situational_conflicts",
        }:
            wfi_context = """
SITUATIONAL CONFLICT

Applicability:
- The diagnosis identifies conflicting rules.
- An implicated triggering event can be meaningfully refined.
- The diagnosis, witness, system description, or declared vocabulary
  provides evidence for the event distinction.

Target and semantics:
- Identify the exact conflicting rules.
- Identify the exact target rule and trigger event requiring differentiation.
- Specialize that event to distinguish the partially conflicting behaviours.
- Co-occurrence of two events in a witness does NOT establish that one event
  is a subtype, specialization, component, or combination of the other.
- Do not manufacture a combined event merely from events that co-occur in
  the conflict witness.
- If no meaningful event specialization is grounded in the current-use-case
  evidence, do not invent one merely to produce a candidate.
"""

        elif normalized_issue in {
            "redundancy",
            "redundancies",
        }:
            wfi_context = """
REDUNDANCY

Applicability:
- The diagnosis identifies a redundant rule, rule pair, or redundant path.
- The implicated triggering event can be meaningfully distinguished.
- The redundancy indicates that intended situations have been represented
  too coarsely.

Target and semantics:
- Identify the exact redundant rule or path selected by the diagnosis.
- Identify the exact target rule and triggering event requiring
  specialization.
- Specialize that event so the intended situation becomes semantically
  distinct from the redundant or overlapping behaviour.
- Preserve the response and all other untargeted rule elements.
- Do not manufacture cosmetic event renamings merely to make redundant rules
  syntactically different.

Paper repair pattern:
  r3:  when SmokeDetectorAlarm then CallEmergencyServices within 7 minutes
  r3': when SevereSmokeDetected then CallEmergencyServices within 7 minutes

The paper example demonstrates the repair pattern only. Do not copy its
vocabulary into another use case unless that vocabulary is independently
grounded there.
"""

        else:
            raise ValueError(
                "event_specialization is not applicable to issue type: "
                f"{issue_type}"
            )

        payload = _build_semantic_payload(
            issue_type=issue_type,
            rules=rules,
            findings=findings,
            repair_operator=repair_operator,
            system_description=system_description,
            existing_events=existing_events,
            existing_measures=existing_measures,
            existing_responses=existing_responses
        )

        return f"""
    {_semantic_common_instructions()}

    SELECTED REPAIR OPERATOR:
    event_specialization

    EVENT SPECIALIZATION:

    WFI-SPECIFIC CONTEXT:
    {wfi_context}

    The repair operator has already been selected by SLEEC-PATCH.

    Instantiate event_specialization only when the diagnosed WFI requires
    a grounded, more-specific triggering event to distinguish the intended
    behaviours.

    Event specialization does NOT require one diagnosed event to be a subtype
    of another diagnosed event.

    The diagnosis identifies why an event distinction is required. It does not
    justify replacing one diagnosed event with another or inventing a new
    event merely to make the candidate syntactically different.

    Follow these requirements strictly:

    1. Identify the exact diagnosed rule or rules involved in the supplied
    diagnosis and witness.

    2. Identify the trigger event context whose associated behaviour must be
    made more specific in order to address the diagnosed WFI.

    3. Use the diagnosis, witness, system description, existing events,
    measures, and responses to determine the semantic distinction required
    by the selected event_specialization operator.

    4. Treat different diagnosed trigger events as evidence of distinct event
    contexts only. Do NOT assume that one diagnosed event is a subtype,
    replacement, or specialization of the other.

    5. Generate only the event-specialization element required to address
    the diagnosed WFI.

    6. Any event introduced or used by the repair must be grounded in:
    - existing_events; OR
    - an event explicitly and unambiguously supported by
        system_description.

    7. Prefer existing declared vocabulary whenever it is sufficient.

    8. NEVER invent an event merely by concatenating:
        <existing event> + <diagnosis phrase/context>

    9. Do not convert a measure, Boolean state, response, or arbitrary
    diagnosis phrase into an event merely to instantiate this operator.

    10. Preserve the stakeholder intent represented by the diagnosed rules.
        Do not transfer contextual restrictions from one event context to
        another unless the supplied diagnosis or system description explicitly
        supports that transfer.

    11. A condition associated with one diagnosed context must not
        automatically be imposed on another context unless the supplied
        diagnosis or system description supports that transfer.

    12. Preserve unaffected trigger conditions, temporal constraints, and
        defeaters unless their modification is necessary to express the
        selected event-specialization repair.

    13. Do not replace this operator with defeater introduction, trigger
        refinement, trigger strengthening, measure specialization, response
        refinement, or new-rule generation.

    14. Do not modify unrelated rules.

    15. The generated candidate must address the supplied diagnosis/witness by
        making the relevant event-triggered behaviours distinguishable.

    16. Before returning the candidate, check:
        - Are the diagnosed rules correctly identified?
        - Are the relevant event contexts grounded?
        - Have you avoided treating two different diagnosed events as if one
        were automatically a subtype of the other?
        - Is every introduced event grounded?
        - Does the candidate address the diagnosed WFI through a grounded
          event distinction?
        - Is stakeholder intent preserved?
        - Are unrelated rules unchanged?
        - Is the proposed rule valid SLEEC syntax?
        - Is the candidate directed at the supplied witness?

    Generate only the semantic/syntactic element required by the selected
    event_specialization operator.

    Do not claim that the generated candidate is formally correct or verified.
    SLEEC-PATCH will apply the candidate to the original specification and
    determine correctness through LEGOS-SLEEC re-analysis.

    OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
    {OPERATOR_EXAMPLES["event_specialization"]}

    Use the ALMI example only to understand the repair pattern.
    Do not copy ALMI vocabulary into another use case.

    CURRENT USE-CASE INPUT:
    {json.dumps(payload, indent=2, ensure_ascii=False)}

    {PATCH_OUTPUT_FORMAT}
    """


def measure_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "measure_specialization"

    normalized_issue = str(issue_type or "").strip().lower()

    if normalized_issue in {
        "conflict",
        "conflicts",
        "situational_conflict",
        "situational_conflicts",
    }:
        wfi_context = """
SITUATIONAL CONFLICT

Applicability:
- The diagnosis identifies conflicting rules.
- An environmental/contextual measure is involved in the conflict.
- The measure is too coarse to distinguish the conflicting contexts.
- The diagnosis or witness supports a more discriminative distinction.

Target and semantics:
- Identify the exact conflicting rules.
- Identify the measure or contextual predicate requiring specialization.
- Specialize the measure to distinguish the conflicting contexts.
- Modify only the measure component required by this operator.
- Do not invent a measure merely because two rules conflict.
"""

    elif normalized_issue in {
        "redundancy",
        "redundancies",
    }:
        wfi_context = """
REDUNDANCY

Applicability:
- The diagnosis identifies a redundant rule, rule pair, or redundant path.
- The overlapping behaviours can be distinguished by an environmental
  or contextual measure.
- The current measure/context representation is too coarse to express the
  intended distinction.

Target and semantics:
- Identify the exact redundant rule or path selected by the diagnosis.
- Identify the environmental/contextual distinction required to partition
  the overlapping behaviours.
- Specialize only the relevant measure.
- Preserve events, responses, temporal constraints, defeaters, and unrelated
  conditions.
- Do not invent a measure merely to make redundant rules syntactically
  different.

Paper repair pattern:
  r3'': when SmokeDetectorAlarm and smokeSeverity = high
        then CallEmergencyServices within 7 minutes

  r4': when SmokeDetectorAlarm and not (smokeSeverity = high)
       then NotifyUserRisk within 2 minutes

The paper example demonstrates the repair pattern only.
Do not copy its vocabulary into another use case unless independently
grounded there.
"""

    else:
        raise ValueError(
            "measure_specialization is not applicable to issue type: "
            f"{issue_type}"
        )

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
measure_specialization

MEASURE SPECIALIZATION:

WFI-SPECIFIC CONTEXT:
{wfi_context}

Instantiate measure_specialization ONLY when the diagnosed WFI depends on
an environmental or contextual measure that is too broad to distinguish
the relevant situations.

Follow these requirements strictly:

1. Identify the exact target rule involved in the diagnosis/witness.

2. Identify the existing measure or contextual predicate that is too broad.

3. Use the diagnosis and witness to determine what environmental/contextual
   distinction is required to eliminate the selected WFI.

4. Search existing_measures and system_description for a grounded,
   more discriminative predicate expressing that distinction.

5. Prefer an already declared measure from existing_measures whenever one
   is sufficient.

6. A specialized measure is permitted only when it is:
   - already present in existing_measures; OR
   - explicitly and unambiguously supported as an environmental/contextual
     predicate by system_description.

7. Do not turn an event, response, or free-text diagnosis phrase
   into a measure merely to make this operator applicable.

8. Do not invent a measure simply because two rules conflict.

9. Preserve the target rule's event, response/action, temporal constraint,
   unrelated conditions, and defeater unless measure specialization itself
   requires changing the selected measure.

10. Do not perform trigger refinement, trigger strengthening,
    defeater introduction, event specialization, response refinement,
    or new-rule generation instead.

11. The specialized measure must be more discriminative than the existing
    measure and must address the diagnosed contextual distinction.

12. Do not modify unrelated rules.

13. Before returning the patch, check:
    - Is the target rule correct?
    - Is there actually a broad measure requiring specialization?
    - Is the new predicate grounded?
    - Is it actually a measure/context predicate?
    - Is it more discriminative than the existing measure?
    - Are the event and response preserved?
    - Is temporal syntax preserved?
    - Does the proposed change address the witness?

14. Generate only a grounded, more discriminative environmental/contextual
    predicate supported by the supplied current-use-case evidence. Do not
    invent a predicate to force a candidate.

The generated measure is a candidate semantic repair. Its formal correctness
will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["measure_specialization"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""


def response_refinement_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    """
    Build the canonical response_refinement prompt.

    The operator name is shared across WFIs, but applicability, target
    selection, diagnosis evidence, and repair semantics remain WFI-specific.
    """
    repair_operator = "response_refinement"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    normalized_issue = str(issue_type or "").strip().lower()

    if normalized_issue in {
        "conflict",
        "conflicts",
        "situational_conflict",
        "situational_conflicts",
    }:
        wfi_instructions = """
WFI:
Situational Conflict

WFI-SPECIFIC RESPONSE REFINEMENT:

Use response_refinement only when the conflict diagnosis/witness shows that
the response of one of the diagnosed conflicting rules is too broad or
insufficiently discriminative for the conflicting situation.

1. Identify the exact diagnosed conflicting rule pair.

2. Identify the exact target rule whose response is to be refined.

3. Use the conflict diagnosis and witness to determine the response
   distinction required to address that conflict.

4. Refine only the target rule's response.

5. Preserve the target rule's trigger, contextual conditions, response
   polarity, temporal constraint, and defeater.

6. Do not modify the other conflicting rule unless it is independently
   selected as the target of another candidate.

7. Do not perform trigger refinement, defeater introduction, rule merging,
   event specialization, or measure specialization instead.

8. The refined response must be grounded in the supplied current-use-case
   evidence.

9. Do not invent a response merely to force the conflict to disappear.
"""

    elif normalized_issue in {
        "redundancy",
        "redundancies",
    }:
        wfi_instructions = """
WFI:
Redundancy

WFI-SPECIFIC RESPONSE REFINEMENT:

Use response_refinement only when the redundancy diagnosis/witness shows
that refining the response of one diagnosed redundant or overlapping rule
can distinguish its required behaviour from the other rule.

1. Identify the exact diagnosed redundant/overlapping rule pair.

2. Identify the exact target rule whose response is too broad or
   insufficiently discriminative.

3. Use the redundancy diagnosis and witness to determine the response
   distinction required to remove the diagnosed overlap.

4. Refine only the target rule's response.

5. Preserve the target rule's trigger, contextual conditions, response
   polarity, temporal constraint, and defeater.

6. Do not remove a rule or propagate a defeater as part of this operator.

7. Do not perform event specialization or measure specialization instead.

8. The refined response must be grounded in the supplied current-use-case
   evidence.

9. Do not invent a response merely to manufacture a distinction between
   otherwise redundant rules.
"""

    elif normalized_issue in {
        "purpose_blocking",
        "purpose blocking",
        "restrictiveness",
        "restrictive",
    }:
        wfi_instructions = """
WFI:
Purpose Blocking / Restrictiveness

WFI-SPECIFIC RESPONSE REFINEMENT:

Use response_refinement only when the diagnosed purpose-blocking WFI shows
that an existing rule's response is too broad for the intended system
purpose in the diagnosed situation.

1. Identify the exact rule involved in the diagnosed purpose blocking.

2. Identify the response whose current meaning is too broad for the
   intended purpose.

3. Use the diagnosed purpose, witness, affected rule, existing vocabulary,
   and system description to determine the required response distinction.

4. Refine only the target rule's response.

5. Preserve the target rule's trigger, contextual conditions, response
   polarity, temporal constraint, and existing defeater.

6. Do not introduce a defeater, refine the trigger, strengthen the trigger,
   decompose the rule, remove the rule, or add an unrelated rule as part of
   this operator.

7. The refined response must be grounded in the CURRENT use case.

8. Prefer an existing response when it expresses the required distinction.

9. A new response may be introduced only when its meaning is explicitly
   and unambiguously supported by the supplied current-use-case evidence.

10. Do not invent functionality merely because it would make the intended
    purpose achievable.
"""

    else:
        raise ValueError(
            "response_refinement is not applicable to issue type: "
            f"{issue_type}"
        )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
response_refinement

RESPONSE REFINEMENT:

The canonical operator is response_refinement. Its WFI-specific
applicability, target selection, and diagnosis interpretation are given
below.

{wfi_instructions}

COMMON RESPONSE-REFINEMENT REQUIREMENTS:

1. Identify the exact target rule from the diagnosis/witness.

2. Identify the existing response that requires refinement.

3. Search existing_responses first for a grounded response expressing the
   required distinction.

4. A new response may be generated only when it is explicitly and
   unambiguously grounded in the supplied current-use-case evidence.

5. Do not create a response merely by attaching diagnosis wording,
   contextual wording, or purpose wording to the existing response name.

6. Do not convert an event, measure, contextual predicate, or free-text
   diagnosis phrase into a response.

7. Change ONLY the target rule's main response.

8. Preserve:
   - the trigger;
   - contextual conditions;
   - response polarity;
   - temporal constraint;
   - defeater; and
   - unrelated rules.

9. The operation value in every returned candidate MUST be exactly:
   response_refinement

10. Before returning a candidate, check:
    - Is the target rule supported by the diagnosis?
    - Is response refinement applicable to this WFI?
    - Is the refined response grounded?
    - Did only the response change?
    - Is response polarity preserved?
    - Is the trigger preserved?
    - Is the temporal constraint preserved?
    - Is the defeater preserved?
    - Does the change address the diagnosed WFI?

The generated result is only a candidate semantic repair.
Do not claim that it resolves the WFI or introduces no new WFIs.
SLEEC-PATCH verification will determine that later.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

CANDIDATE REQUIREMENT:
Return up to 3 genuinely semantically distinct response refinements when
the supplied evidence supports them. Do not manufacture cosmetic response
renamings merely to produce multiple candidates.

{PATCH_OUTPUT_FORMAT}
"""

def new_rule_generation_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "new_rule_generation"

    normalized_issue = str(issue_type or "").strip().lower()

    if normalized_issue not in {
        "concern",
        "concerns",
        "insufficiency",
        "insufficiencies",
    }:
        raise ValueError(
            "new_rule_generation is not applicable to issue type: "
            f"{issue_type}"
        )

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
new_rule_generation

NEW-RULE GENERATION:

APPLICABILITY:
New-rule generation is applicable when the diagnosed concern identifies
normative behaviour not captured by the existing rules.

REPAIR SEMANTICS:
Introduce a new obligation that directly prevents or addresses the diagnosed
concern. The new rule must capture the missing normative behaviour identified
by the concern and must not duplicate behaviour already specified by the
existing rules.

Instantiate new_rule_generation ONLY when the diagnosis/witness demonstrates
missing normative behaviour that is not already captured by the specification.

Follow these requirements strictly:

1. Identify the exact missing normative behaviour demonstrated by the
   diagnosis and witness.

2. Determine the event or trigger required for that missing behaviour.

3. Determine any contextual measures required by the diagnosis.

4. Determine the required system response.

4a. Preserve the response polarity required by the diagnosed missing
    normative behaviour. If the diagnosis requires `not Response`, the
    generated rule must preserve `not Response`; if it requires `Response`,
    preserve `Response`. Do not reverse the required response merely to
    "prevent" or "address" the concern.

5. Check the existing rules before generating a new rule.
   Do not generate a duplicate or semantically equivalent rule.

6. Every event used in the new rule must be grounded in existing_events or
   explicitly and unambiguously supported as an event by system_description.

7. Every measure/context predicate used in the new rule must be grounded in
   existing_measures or explicitly and unambiguously supported as a measure
   by system_description.

8. Every response used in the new rule must be grounded in existing_responses
   or explicitly and unambiguously supported as a system capability by
   system_description.

9. Diagnosis and witness determine WHAT normative gap must be addressed.
   Do not automatically transform their natural-language wording into new
   formal vocabulary.

10. Prefer composing the new rule from already declared events, measures,
    and responses.

11. Do not invent a new event, measure, or response merely to make
    new_rule_generation applicable.

12. Generate ONE additional normative rule for the selected missing
    behaviour unless the output contract explicitly requires otherwise.

13. Do not rewrite an existing rule and label it new_rule_generation.

14. Do not introduce deterministic repairs such as defeaters or trigger
    strengthening instead.

15. Preserve any temporal requirement explicitly required by the diagnosis
    or witness.

16. The generated rule must directly prevent or address the supplied witness
    concern.

17. Before returning the patch, check:
    - Does the witness demonstrate missing normative behaviour?
    - Is a genuinely new rule required?
    - Are all events grounded?
    - Are all measures grounded?
    - Is the response grounded?
    - Does an equivalent rule already exist?
    - Is temporal information preserved?
    - Is the new rule valid SLEEC syntax?
    - Does the new rule address the witness?

18. Construct the candidate rule only from grounded semantic elements
    supported by the supplied current-use-case evidence. Do not invent
    unsupported vocabulary or normative behaviour to force a candidate.

The generated rule is a candidate semantic repair. Its formal correctness
will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["new_rule_generation"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""

def build_prompt(
    issue_type,
    rules,
    findings,
    repair_operator,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
    ):
    prompt_builders = {
        "event_specialization": event_specialization_prompt,
        "measure_specialization": measure_specialization_prompt,
        "response_refinement": response_refinement_prompt,
        "new_rule_generation": new_rule_generation_prompt,
    }

    if repair_operator not in LLM_SEMANTIC_OPERATORS:
        raise ValueError(
            f"{repair_operator} is deterministic and must be generated "
            f"by Python script, not GPT."
        )

    builder = prompt_builders.get(repair_operator)

    if builder is None:
        raise ValueError(
            f"No prompt builder is registered for LLM semantic operator: "
            f"{repair_operator}"
        )

    return builder(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )


# PATCH RANKING — Section C
def patch_quality_ranking_prompt(
    patch,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    payload = {
        "system_description": system_description,
        "original_rule": patch.get("original_rule", ""),
        "proposed_rule": patch.get("proposed_rule", ""),
        "operation": patch.get("operation", ""),
        "natural_language_explanation": patch.get(
            "natural_language_explanation", patch.get("explanation", "")
        ),
        "missing_element": patch.get("missing_element", ""),
        "issue_type": patch.get("issue_type", ""),
        "selected_issue": patch.get("selected_issue", ""),
        "affected_rules": patch.get("affected_rules", []),
        "diagnosis_context": patch.get("diagnosis_context", ""),
        "existing_events": existing_events or [],
        "existing_measures": existing_measures or [],
        "existing_responses": existing_responses or []
    }

    return f"""
The SLEEC repair below has ALREADY passed formal verification.
Do NOT assess formal correctness and do NOT propose a different repair.

Assess only:

SEMANTIC CLARITY (0-100)
Prefer specific, unambiguous, domain-grounded events, measures, and responses.

VOCABULARY INTERPRETATION RULES:
- existing_events, existing_measures, and existing_responses contain concepts
  already declared or already used in the current SLEEC specification.
- Do NOT classify or penalize a concept as newly introduced merely because it
  is absent from the individual original_rule.
- A concept is genuinely new only if it appears in proposed_rule but is absent
  from existing_events, existing_measures, existing_responses, and original_rule.
- Reuse of a declared concept should normally support semantic clarity when the
  concept is used consistently with its domain meaning.
- For a genuinely new concept, assess whether it is specific, unambiguous,
  domain-grounded, explained by the repair rationale/system description, and
  meaningfully distinct from existing vocabulary.
- Penalize genuinely new generic placeholders such as RiskHigh, ConditionMet,
  SituationBad, UserIsOk, NormalState, and SpecialCase.
- Do NOT penalize declared concepts such as riskLevel, userOccupied,
  humanAssents, SmokeDetectorAlarm, or userDisablesAlarm when they appear in
  the supplied existing vocabulary.

INTERPRETABILITY (0-100)
Prefer preservation of apparent stakeholder intent, an understandable rationale,
minimal dependence on unstated context, and descriptive predicates.
Penalize unexplained action changes or contextual distinctions.

AND, OR, NOT, WHEN, THEN, UNLESS, and WITHIN are SLEEC syntax, not predicates.
If proposed_rule contains multiple rules, assess the complete repair.

INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

Return ONLY this raw JSON object:
{{
  "semantic_clarity": 0,
  "semantic_clarity_reason": "one concise reason",
  "interpretability": 0,
  "interpretability_reason": "one concise reason"
}}
"""
