import json
import re


PATCH_OUTPUT_FORMAT = """
Return ONLY a raw JSON array.

The repair operator has already been selected by SLEEC-PATCH.

Your task is to instantiate that selected operator and generate the
missing semantic/syntactic element required by it.

Each candidate patch MUST use this structure:

[
  {
    "patch_id": "p1",
    "issue_type": "<diagnosed issue type>",
    "operation": "<selected repair operator>",

    "target_rule_id": "<target rule id, or empty only when the selected operator creates a new rule>",
    "original_rule": "<exact original SLEEC rule, or empty only when the selected operator creates a new rule>",

    "missing_element": "<the semantic/syntactic element generated by the selected operator>",
    "proposed_rule": "<complete candidate SLEEC rule containing the generated element>",

    "grounding_evidence": {
      "source": "<system_description|diagnosis|witness|existing_vocabulary>",
      "source_terms": [
        "<exact supporting term or formal identifier from the claimed source>"
      ],
      "existing_element": "<existing element being specialized/refined, or empty for new-rule generation when appropriate>",
      "new_element": "<the generated semantic/syntactic element>",
      "relationship": "<how the cited evidence supports the generated element>"
    },

    "natural_language_explanation": "<brief explanation of how the generated element instantiates the selected repair operator for the diagnosed WFI>",

    "modification_cost": 1,
    "new_events_added": 0,
    "new_measures_added": 0,
    "new_capabilities_added": 0,
    "new_rules_added": 0,
    "defeaters_added": 0
  }
]

IMPORTANT:

- The selected repair operator is fixed. Do not choose another operator.
- Generate only the semantic/syntactic element required by that operator.
- Do not claim that the candidate is formally correct or verified.
- Do not claim that the targeted WFI has been eliminated.
- Do not claim that the candidate introduces no additional WFIs.
- Formal correctness is determined later by SLEEC-PATCH through
  LEGOS-SLEEC re-analysis.
- Do not modify unrelated rules.
- Set the *_added fields according to the actual candidate repair.
- Do NOT use markdown.
- Do NOT use ```json.
- Do NOT add text before or after the JSON.
- The response MUST start with [ and end with ].
"""


LLM_SEMANTIC_OPERATORS = [
    "event_specialization",
    "measure_specialization",
    "capability_refinement",
    "new_rule_generation"
]


def build_sleec_syntax_bank(rules):
    rules = rules or []
    rule_texts = [
        str(rule.get("raw") or rule.get("text") or "").strip()
        if isinstance(rule, dict)
        else str(rule or "").strip()
        for rule in rules
    ]
    rule_texts = [text for text in rule_texts if text]

    observed = []
    if any(" unless " in text.lower() for text in rule_texts):
        observed.append("unless exceptions with optional alternative responses")
    if any(" within " in text.lower() for text in rule_texts):
        observed.append("within time bounds")
    if any(re.search(r"\{[A-Za-z_][A-Za-z0-9_]*\}", text) for text in rule_texts):
        observed.append("boolean measures wrapped in braces")
    if any(re.search(r"\{?[A-Za-z_][A-Za-z0-9_]*\}?\s*[<>=]\s*[A-Za-z0-9_]+", text) for text in rule_texts):
        observed.append("measure comparisons")
    if any(re.search(r"\b(?:and|or|not)\b", text, flags=re.IGNORECASE) for text in rule_texts):
        observed.append("and/or/not logical conditions")

    examples = rule_texts[:5]

    return {
        "allowed_rule_templates": [
            "RuleName when Trigger then Action",
            "RuleName when Trigger and Condition then Action",
            "RuleName when Trigger then Action within Number seconds",
            "RuleName when Trigger then Action unless Condition",
            "RuleName when Trigger then Action unless Condition then AlternativeAction",
        ],
        "observed_syntax_features": observed,
        "local_rule_examples": examples,
        "instruction": (
            "Use only these observed SLEEC syntax forms and the supplied "
            "vocabulary. Do not invent grammar constructs."
        )
    }


SLEEC_SYNTAX_CONTRACT = """
SLEEC SYNTAX CONTRACT:
Use only the SLEEC syntax already present in the input specification.

Allowed declaration lines:
- event EventName
- measure measureName:boolean
- measure measureName:numeric
- constant ConstantName = value

Allowed rule shapes:
- RuleName when Trigger then Action
- RuleName when Trigger and Condition then Action
- RuleName when Trigger then Action within Number seconds
- RuleName when Trigger then Action
       unless Condition then AlternativeAction
- RuleName when Trigger then Action
       unless Condition

Allowed condition syntax:
- and, or, not
- parentheses for grouping
- boolean measures as {measureName}
- numeric comparisons such as {measureName} > ConstantName

Forbidden syntax:
- Do not use IF, ELSE, REQUIRES, BECAUSE, SHOULD, MUST, UNTIL, EXCEPT, IMPLIES, or arrows.
- Do not invent new SLEEC keywords.
- Do not put prose, bullet points, or comments inside proposed_rule.
- Do not wrap the whole rule in parentheses.
- Do not output def_start, def_end, rule_start, or rule_end inside proposed_rule.
- Do not output declaration lines inside proposed_rule.

Vocabulary accounting:
- If missing_element is a new event, set new_events_added to 1.
- If missing_element is a new measure, set new_measures_added to 1.
- If missing_element is a new response/capability, set new_capabilities_added to 1.
- If the patch adds a new rule, set new_rules_added to 1.
- Otherwise the corresponding counter must be 0.

The generated candidate must follow this syntax contract exactly.
Do not invent new SLEEC syntax to express the selected repair operator.
"""


SLEEC_FEW_SHOT_SYNTAX_EXAMPLES = """
FEW-SHOT SLEEC SYNTAX EXAMPLES:
These examples teach syntax shape only. Do not copy their domain vocabulary.

Example 1: edit an existing event trigger
Original rule:
r1 when BroadEvent then SafeAction
Correct proposed_rule:
r1 when SpecificEvent then SafeAction

Example 2: preserve an unless branch
Original rule:
r2 when RequestAction then DoAction
   unless {unsafeState} then StopAction
Correct proposed_rule:
r2 when SpecificRequestAction then DoAction
   unless {unsafeState} then StopAction

Example 3: preserve temporal syntax
Original rule:
r3 when EmergencyEvent then NotifyHuman within 60 seconds
Correct proposed_rule:
r3 when SpecificEmergencyEvent then NotifyHuman within 60 seconds

Example 4: add one new rule
Correct proposed_rule:
r_new when MissingConditionEvent and {relevantState} then RequiredAction

"""



OPERATOR_EXAMPLES = {

'event_specialization': '''EXAMPLE: EVENT SPECIALIZATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
Different emergency events may require different responses.
A fire-related emergency and a human-on-floor emergency must not
automatically be treated as the same situation.

Original rules:

r1 when SmokeDetectorAlarm
   then CallingFireMan within 5 minutes

r2 when HumanOnFloor and not humanAssents
   then not CallEmergencyServices within 500 seconds

Diagnosis:
The behaviours concern different emergency situations.
SmokeDetectorAlarm represents a fire-related emergency, whereas
HumanOnFloor represents a different emergency context in which
human assent may be relevant.

Selected operator:
event_specialization

Generation task:
Use the diagnosis and witness to identify the semantic distinction
required by the selected operator.

Generate only a grounded finer-grained event that expresses that
distinction.

Search existing_events first. A new event may be generated from the
system description only when its semantics are explicitly and
unambiguously supported there.

IMPORTANT:
Do NOT specialize SmokeDetectorAlarm by attaching the consent condition
from the second rule.

INVALID examples:

SmokeDetectorAlarmWithoutHumanAssent
SmokeDetectorAlarmWhileHumanOnFloor
HumanOnFloorFireEmergency

These events are invalid unless their semantics are explicitly supported
by the supplied current-use-case vocabulary or system description.

Do NOT infer that CallingFireMan requires human assent merely because
humanAssents occurs in another rule.

Preserve:
- the original response;
- the temporal constraint;
- unrelated conditions; and
- defeaters.

The diagnosis and witness identify WHY event specialization is required.
Their natural-language wording must not automatically be converted into
a new event.''',


'measure_specialization': '''EXAMPLE: MEASURE SPECIALIZATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:

r4 when SmokeDetectorAlarm and not humanConfirm
   then CallEmergencyServices within 5 minutes

r5 when HumanOnFloor and not humanConfirm
   then not CallEmergencyServices within 500 seconds

Diagnosis:
Both behaviours contain contextual information represented by
humanConfirm. The diagnosed conflict requires a more discriminative
environmental/contextual distinction.

Selected operator:
measure_specialization

Generation task:
Use the diagnosis and witness to determine what environmental/contextual
distinction is required.

Generate only the grounded, more discriminative measure required by the
selected operator.

Search existing_measures first. A new measure may be generated from the
system description only when the environmental/contextual concept is
explicitly and unambiguously supported there.

For example, ALMI may contain distinctions involving concepts such as:

humanAssent

or:

humanConscious

These concepts must NOT be introduced merely because they appear useful.
They may be used only when grounded in the supplied current-use-case input.

The diagnosis and witness identify WHY measure specialization is required.
Their natural-language wording must not automatically be converted into
a new measure.

Preserve:
- the relevant event;
- the response;
- the temporal constraint;
- unrelated conditions; and
- defeaters.

Do NOT invent an environmental predicate merely to force a candidate.''',


'capability_refinement': '''EXAMPLE: CAPABILITY REFINEMENT — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
The specification contains emergency-related responses such as:

CallingFireMan

and:

CallEmergencyServices

These responses represent different system capabilities and must not
automatically be treated as interchangeable.

Example rule:

r1 when SmokeDetectorAlarm
   then CallEmergencyServices within 5 minutes

Diagnosis:
The diagnosed behaviour requires a more specific response than the broad
CallEmergencyServices capability.

Selected operator:
capability_refinement

Generation task:
Use the diagnosis and witness to determine what response distinction is
required.

Generate only the grounded, more-specific capability required by the
selected operator.

Search existing_responses first. A new capability may be generated from
the system description only when the capability is explicitly and
unambiguously supported there.

For example, if the supplied current-use-case evidence establishes
CallingFireMan as the required more-specific response for the diagnosed
fire-related behaviour, it may be used as the refined capability.

Do NOT invent capabilities such as:

CallSpecialEmergencyServices
CallEmergencyServicesForFire
CallEmergencyServicesForUnconsciousHuman

unless those capabilities are explicitly supported by the supplied
current-use-case evidence.

The diagnosis and witness identify WHY capability refinement is required.
Their natural-language wording must not automatically be converted into
a new capability.

Preserve:
- the trigger;
- contextual conditions;
- the temporal constraint; and
- defeaters.

Change only the response required by capability_refinement.''',


'new_rule_generation': '''EXAMPLE: NEW RULE GENERATION — ALMI

This example demonstrates the repair pattern and grounding requirements only.
Do not copy ALMI vocabulary into another use case.

ALMI context:
The specification contains emergency situations such as:

HumanOnFloor

and system responses such as:

CallEmergencyServices

Diagnosis:
A LEGOS-SLEEC witness identifies missing normative behaviour involving
HumanOnFloor that must be addressed by an additional rule.

Selected operator:
new_rule_generation

Generation task:
Use the diagnosed rules, witness, diagnosis, system description, and
existing vocabulary to identify the missing normative behaviour.

Generate only the additional normative rule required by the selected
operator.

Every element used in the generated rule must be grounded:
- events in existing_events or explicitly supported by system_description;
- measures in existing_measures or explicitly supported by system_description;
- responses in existing_responses or explicitly supported by system_description.

Grounded structural pattern:

If the supplied diagnosis, witness, existing vocabulary, and ALMI system
description establish that HumanOnFloor requires CallEmergencyServices,
the following form illustrates the operator:

r_new when HumanOnFloor
      then CallEmergencyServices

This is a structural example only.
The current-use-case evidence must justify the generated normative behaviour.

Do NOT invent unsupported responses such as:

CallDoctor

and do NOT invent contextual predicates such as:

{patientCritical}
{hospitalAvailable}
{familyPermission}

unless those concepts are explicitly grounded in the supplied
current-use-case evidence.

Do not create unnecessary new events, measures, or capabilities.

The generated rule must directly address the diagnosed witness concern
and must not duplicate an existing rule.

Formal correctness of the generated candidate is determined later by
SLEEC-PATCH through LEGOS-SLEEC re-analysis.'''
}
def _build_semantic_payload(
    issue_type,
    rules,
    findings,
    repair_operator,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    """
    Build the common input payload used by all LLM semantic repair operators.
    Operator-specific prompt functions decide how this information may be used.
    """
    existing_events = existing_events or []
    existing_measures = existing_measures or []
    existing_responses = existing_responses or []

    return {
        "issue_type": issue_type,
        "repair_operator": repair_operator,
        "sleec_findings": findings,
        "rules": rules,
        "syntax_bank": build_sleec_syntax_bank(rules),
        "system_description": system_description,
        "existing_events": existing_events,
        "existing_measures": existing_measures,
        "existing_responses": existing_responses
    }


def _semantic_common_instructions():
    """
    Rules shared by all four LLM-assisted semantic repair operators.
    """
    return f"""
You are an expert in SLEEC, normative requirements, semantic requirement
refinement, and stakeholder-centered rule repair.

SLEEC-PATCH has already selected the semantic repair operator.

Your task is ONLY to instantiate that selected operator.

Do NOT select another repair operator.

Do NOT generate deterministic repairs such as:
- trigger_refinement
- defeater_introduction
- rule_merging
- rule_removal
- trigger_strengthening
- rule_decomposition

COMMON REQUIREMENTS:

1. Work only on the diagnosed WFI and its supplied diagnosis/witness.

2. Do not rewrite the complete SLEEC specification.

3. Do not modify unrelated rules.

4. Preserve stakeholder intent and the original domain meaning.

5. Use existing declared vocabulary whenever it is sufficient.

6. Every newly introduced semantic element must be grounded in the
   supplied current-use-case evidence.

7. Prefer explicit existing vocabulary whenever possible.

8. system_description may support a new semantic element only when the
   concept is explicit and unambiguous.

9. Diagnosis and witness primarily identify WHY a semantic distinction
   or missing behaviour is required. Do not automatically convert their
   natural-language wording into a new formal event, measure, or response.

10. Do NOT claim grounding from:
    - general knowledge;
    - common sense;
    - an unstated domain assumption;
    - the ALMI worked example;
    - a concept that merely sounds plausible.

11. Do NOT copy ALMI concepts into the current use case unless those
    concepts are independently grounded in the current-use-case input.

12. Populate grounding_evidence for every proposed semantic repair.

13. source_terms must contain exact supporting words, phrases, or formal
    identifiers from the claimed current-use-case source.

14. The proposed patch must directly address the supplied diagnosis and
    witness. A semantically plausible rewrite that leaves the selected
    WFI unchanged is not a successful repair.

15. Preserve diagnosed temporal information. If the affected rule or
    diagnosis contains WITHIN or another temporal constraint, preserve it
    unless the selected semantic repair explicitly requires refinement.

16. Every proposed rule must follow valid SLEEC syntax.

17. Generate only grounded semantic elements supported by the supplied
    current-use-case evidence. Do not invent unsupported vocabulary merely
    to force a candidate repair.

18. Do not decide whether the selected operator is applicable. The repair
    operator has already been selected by SLEEC-PATCH.

19. Do not decide whether the candidate is formally correct. Formal
    correctness is established later by applying the candidate to the
    original SLEEC specification and re-analyzing it with LEGOS-SLEEC.

SLEEC SYNTAX CONTRACT:
{SLEEC_SYNTAX_CONTRACT}

SLEEC SYNTAX EXAMPLES:
{SLEEC_FEW_SHOT_SYNTAX_EXAMPLES}
"""


def event_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "event_specialization"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
event_specialization

EVENT SPECIALIZATION:

Instantiate event_specialization ONLY when the diagnosed WFI can be repaired
by replacing or specializing a broad trigger event with a grounded,
finer-grained event.

Follow these requirements strictly:

1. Identify the exact target rule involved in the supplied diagnosis/witness.

2. Identify the broad event in that target rule that requires specialization.

3. Use the diagnosis and witness to determine what semantic distinction is
   required to eliminate the selected WFI.

4. Search existing_events and system_description for a grounded,
   finer-grained event expressing that distinction.

5. Prefer an already declared event from existing_events whenever one is
   sufficient.

6. A specialized event is permitted only when it is:
   - already present in existing_events; OR
   - explicitly and unambiguously supported as an event by
     system_description.

7. NEVER construct a new event merely by concatenating:
       <existing event> + <diagnosis phrase/context>

8. Do not convert a measure, Boolean state, response, or diagnosis phrase
   into an event merely to make this operator applicable.

9. Preserve the original response/action, temporal constraint, contextual
   conditions, and defeater unless event specialization itself requires
   their modification.

10. Do not introduce a defeater, trigger refinement, trigger strengthening,
    measure specialization, capability refinement, or new rule instead.

11. Do not modify unrelated rules.

12. The specialized event must distinguish the diagnosed situation and the
    proposed rule must be intended to eliminate the supplied witness.

13. Before returning the patch, check:
    - Is the target rule correct?
    - Is the original event genuinely too broad?
    - Is the specialized event grounded?
    - Is it actually an event?
    - Does it distinguish the diagnosed situation?
    - Is the original response preserved?
    - Is temporal syntax preserved?
    - Is the proposed rule valid SLEEC syntax?
    - Does the proposed change address the witness?

14. Generate only a grounded finer-grained event supported by the supplied
    current-use-case evidence. Do not invent an event to force a candidate.

The generated event is a candidate semantic repair. Its formal correctness
will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["event_specialization"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""


def measure_specialization_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "measure_specialization"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
measure_specialization

MEASURE SPECIALIZATION:

Instantiate measure_specialization ONLY when the diagnosed WFI depends on
an environmental or contextual measure that is too broad to distinguish
the relevant situations.

Follow these requirements strictly:

1. Identify the exact target rule involved in the diagnosis/witness.

2. Identify the existing measure or contextual predicate that is too broad.

3. Use the diagnosis and witness to determine what environmental/contextual
   distinction is required to eliminate the selected WFI.

4. Search existing_measures and system_description for a grounded,
   more discriminative predicate expressing that distinction.

5. Prefer an already declared measure from existing_measures whenever one
   is sufficient.

6. A specialized measure is permitted only when it is:
   - already present in existing_measures; OR
   - explicitly and unambiguously supported as an environmental/contextual
     predicate by system_description.

7. Do not turn an event, response, capability, or free-text diagnosis phrase
   into a measure merely to make this operator applicable.

8. Do not invent a measure simply because two rules conflict.

9. Preserve the target rule's event, response/action, temporal constraint,
   unrelated conditions, and defeater unless measure specialization itself
   requires changing the selected measure.

10. Do not perform trigger refinement, trigger strengthening,
    defeater introduction, event specialization, capability refinement,
    or new-rule generation instead.

11. The specialized measure must be more discriminative than the existing
    measure and must address the diagnosed contextual distinction.

12. Do not modify unrelated rules.

13. Before returning the patch, check:
    - Is the target rule correct?
    - Is there actually a broad measure requiring specialization?
    - Is the new predicate grounded?
    - Is it actually a measure/context predicate?
    - Is it more discriminative than the existing measure?
    - Are the event and response preserved?
    - Is temporal syntax preserved?
    - Does the proposed change address the witness?

14. Generate only a grounded, more discriminative environmental/contextual
    predicate supported by the supplied current-use-case evidence. Do not
    invent a predicate to force a candidate.

The generated measure is a candidate semantic repair. Its formal correctness
will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["measure_specialization"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""


def capability_refinement_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "capability_refinement"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
capability_refinement

CAPABILITY REFINEMENT:

Instantiate capability_refinement ONLY when the response/action in the
target rule is too broad and the diagnosed WFI requires a grounded,
more-specific system capability.

Follow these requirements strictly:

1. Identify the exact target rule involved in the diagnosis/witness.

2. Identify the broad response/action that requires refinement.

3. Use the diagnosis and witness to determine what response distinction is
   required to eliminate the selected WFI.

4. Search existing_responses and system_description for a grounded,
   more-specific capability expressing that distinction.

5. Prefer an already declared response from existing_responses whenever one
   is sufficient.

6. A refined capability is permitted only when it is:
   - already present in existing_responses; OR
   - explicitly and unambiguously supported as a system capability by
     system_description.

7. Do not create a capability by attaching diagnosis wording to the
   existing response name.

8. Do not convert an event, measure, contextual state, or diagnosis phrase
   into a capability merely to make this operator applicable.

9. Preserve the target rule's trigger, contextual conditions, temporal
   constraint, and defeater unless capability refinement itself requires
   modification of the response.

10. Do not perform event specialization, measure specialization,
    trigger refinement, defeater introduction, or new-rule generation
    instead.

11. The new capability must be semantically more specific than the original
    response and must address the diagnosed behaviour.

12. Do not modify unrelated rules.

13. Before returning the patch, check:
    - Is the target rule correct?
    - Is the original response genuinely too broad?
    - Is the refined capability grounded?
    - Is it actually a system response/capability?
    - Is it more specific than the original response?
    - Is the trigger preserved?
    - Is temporal syntax preserved?
    - Does the proposed change address the witness?

14. Generate only a grounded, more-specific capability supported by the
    supplied current-use-case evidence. Do not invent a capability to force
    a candidate.

The generated capability is a candidate semantic repair. Its formal
correctness will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["capability_refinement"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""


def new_rule_generation_prompt(
    issue_type,
    rules,
    findings,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    repair_operator = "new_rule_generation"

    payload = _build_semantic_payload(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        repair_operator=repair_operator,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )

    return f"""
{_semantic_common_instructions()}

SELECTED REPAIR OPERATOR:
new_rule_generation

NEW-RULE GENERATION:

Instantiate new_rule_generation ONLY when the diagnosis/witness demonstrates
missing normative behaviour that cannot be represented by merely refining an
existing rule.

Follow these requirements strictly:

1. Identify the exact missing normative behaviour demonstrated by the
   diagnosis and witness.

2. Determine the event or trigger required for that missing behaviour.

3. Determine any contextual measures required by the diagnosis.

4. Determine the required system response.

5. Check the existing rules before generating a new rule.
   Do not generate a duplicate or semantically equivalent rule.

6. Every event used in the new rule must be grounded in existing_events or
   explicitly and unambiguously supported as an event by system_description.

7. Every measure/context predicate used in the new rule must be grounded in
   existing_measures or explicitly and unambiguously supported as a measure
   by system_description.

8. Every response used in the new rule must be grounded in existing_responses
   or explicitly and unambiguously supported as a system capability by
   system_description.

9. Diagnosis and witness determine WHAT normative gap must be addressed.
   Do not automatically transform their natural-language wording into new
   formal vocabulary.

10. Prefer composing the new rule from already declared events, measures,
    and responses.

11. Do not invent a new event, measure, or capability merely to make
    new_rule_generation applicable.

12. Generate ONE additional normative rule for the selected missing
    behaviour unless the output contract explicitly requires otherwise.

13. Do not rewrite an existing rule and label it new_rule_generation.

14. Do not introduce deterministic repairs such as defeaters or trigger
    strengthening instead.

15. Preserve any temporal requirement explicitly required by the diagnosis
    or witness.

16. The generated rule must directly prevent or address the supplied witness
    concern.

17. Before returning the patch, check:
    - Does the witness demonstrate missing normative behaviour?
    - Is a genuinely new rule required?
    - Are all events grounded?
    - Are all measures grounded?
    - Is the response grounded?
    - Does an equivalent rule already exist?
    - Is temporal information preserved?
    - Is the new rule valid SLEEC syntax?
    - Does the new rule address the witness?

18. Construct the candidate rule only from grounded semantic elements
    supported by the supplied current-use-case evidence. Do not invent
    unsupported vocabulary or normative behaviour to force a candidate.

The generated rule is a candidate semantic repair. Its formal correctness
will be determined later by SLEEC-PATCH verification.

OPERATOR-SPECIFIC ALMI WORKED EXAMPLE:
{OPERATOR_EXAMPLES["new_rule_generation"]}

Use the ALMI example only to understand the repair pattern.
Do not copy ALMI vocabulary into the current use case.

CURRENT USE-CASE INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

{PATCH_OUTPUT_FORMAT}
"""


def build_prompt(
    issue_type,
    rules,
    findings,
    repair_operator,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    prompt_builders = {
        "event_specialization": event_specialization_prompt,
        "measure_specialization": measure_specialization_prompt,
        "capability_refinement": capability_refinement_prompt,
        "new_rule_generation": new_rule_generation_prompt,
    }

    if repair_operator not in LLM_SEMANTIC_OPERATORS:
        raise ValueError(
            f"{repair_operator} is deterministic and must be generated "
            f"by Python script, not GPT."
        )

    builder = prompt_builders.get(repair_operator)

    if builder is None:
        raise ValueError(
            f"No prompt builder is registered for LLM semantic operator: "
            f"{repair_operator}"
        )

    return builder(
        issue_type=issue_type,
        rules=rules,
        findings=findings,
        system_description=system_description,
        existing_events=existing_events,
        existing_measures=existing_measures,
        existing_responses=existing_responses
    )


# PATCH RANKING — Section C
def patch_quality_ranking_prompt(
    patch,
    system_description="",
    existing_events=None,
    existing_measures=None,
    existing_responses=None
):
    payload = {
        "system_description": system_description,
        "original_rule": patch.get("original_rule", ""),
        "proposed_rule": patch.get("proposed_rule", ""),
        "operation": patch.get("operation", ""),
        "natural_language_explanation": patch.get(
            "natural_language_explanation", patch.get("explanation", "")
        ),
        "missing_element": patch.get("missing_element", ""),
        "issue_type": patch.get("issue_type", ""),
        "selected_issue": patch.get("selected_issue", ""),
        "affected_rules": patch.get("affected_rules", []),
        "diagnosis_context": patch.get("diagnosis_context", ""),
        "existing_events": existing_events or [],
        "existing_measures": existing_measures or [],
        "existing_responses": existing_responses or []
    }

    return f"""
The SLEEC repair below has ALREADY passed formal verification.
Do NOT assess formal correctness and do NOT propose a different repair.

Assess only:

SEMANTIC CLARITY (0-100)
Prefer specific, unambiguous, domain-grounded events, measures, and responses.

VOCABULARY INTERPRETATION RULES:
- existing_events, existing_measures, and existing_responses contain concepts
  already declared or already used in the current SLEEC specification.
- Do NOT classify or penalize a concept as newly introduced merely because it
  is absent from the individual original_rule.
- A concept is genuinely new only if it appears in proposed_rule but is absent
  from existing_events, existing_measures, existing_responses, and original_rule.
- Reuse of a declared concept should normally support semantic clarity when the
  concept is used consistently with its domain meaning.
- For a genuinely new concept, assess whether it is specific, unambiguous,
  domain-grounded, explained by the repair rationale/system description, and
  meaningfully distinct from existing vocabulary.
- Penalize genuinely new generic placeholders such as RiskHigh, ConditionMet,
  SituationBad, UserIsOk, NormalState, and SpecialCase.
- Do NOT penalize declared concepts such as riskLevel, userOccupied,
  humanAssents, SmokeDetectorAlarm, or userDisablesAlarm when they appear in
  the supplied existing vocabulary.

INTERPRETABILITY (0-100)
Prefer preservation of apparent stakeholder intent, an understandable rationale,
minimal dependence on unstated context, and descriptive predicates.
Penalize unexplained action changes or contextual distinctions.

AND, OR, NOT, WHEN, THEN, UNLESS, and WITHIN are SLEEC syntax, not predicates.
If proposed_rule contains multiple rules, assess the complete repair.

INPUT:
{json.dumps(payload, indent=2, ensure_ascii=False)}

Return ONLY this raw JSON object:
{{
  "semantic_clarity": 0,
  "semantic_clarity_reason": "one concise reason",
  "interpretability": 0,
  "interpretability_reason": "one concise reason"
}}
"""
